using SsalKit.DependencyInjection.Generator.Models;
using SsalKit.Generators.Toolkit;

namespace SsalKit.DependencyInjection.Generator.Emission;

/// <summary>
/// Writes the implementation class for one <c>[ServiceFactory]</c> interface: an
/// <see langword="internal"/> <see langword="sealed"/> class that captures an
/// <c>IServiceProvider</c> and forwards its single method to <c>GetRequiredKeyedService</c>,
/// passing the enum argument through verbatim as the service key.
/// </summary>
/// <remarks>
/// <para>
/// The class is emitted into the reserved <c>SsalKit.DependencyInjection.Generated</c> namespace
/// (mirroring the interface's own namespace beneath it) rather than into the interface's namespace,
/// so it can never shadow or collide with a consumer type. It is always <see langword="internal"/>:
/// nothing outside the assembly ever names it -- the generated <c>Add{Assembly}Services</c> method
/// registers it as the interface, which is all consumers resolve.
/// </para>
/// <para>
/// Every referenced type is <c>global::</c>-qualified and <c>GetRequiredKeyedService</c> is called
/// through its declaring static class rather than as an extension method, so the file needs no
/// <c>using</c> directives at all and cannot be affected by whatever else is in scope in the
/// consumer's compilation.
/// </para>
/// </remarks>
internal static class ServiceFactoryImplementationEmitter
{
    private const string ServiceProviderType = "global::System.IServiceProvider";
    private const string KeyedServiceExtensionsType =
        "global::Microsoft.Extensions.DependencyInjection.ServiceProviderKeyedServiceExtensions";

    /// <summary>
    /// The backing field, always accessed through <c>this.</c> in the generated method body: the
    /// interface's own parameter name is reused verbatim, and a parameter named <c>_provider</c>
    /// would otherwise shadow the field and silently change what the lookup runs against.
    /// </summary>
    private const string ProviderField = "_provider";

    public static string Emit(ServiceFactoryModel model)
    {
        var writer = new IndentedCodeWriter();
        writer.WriteAutoGeneratedHeader();

        using (writer.Block("namespace " + model.ImplementationNamespace))
        {
            WriteImplementationClass(writer, model);
        }

        return writer.ToString();
    }

    private static void WriteImplementationClass(IndentedCodeWriter writer, ServiceFactoryModel model)
    {
        writer.WriteDocLines(
            "<summary>",
            "The generated implementation of <see cref=\"" + model.InterfaceTypeFqn + "\"/>, which resolves",
            "a keyed service using the value passed to <c>" + model.MethodName + "</c> as the service key.",
            "</summary>",
            "<remarks>Generated by the SsalKit.DependencyInjection source generator. Do not edit by hand.</remarks>");

        using (writer.Block("internal sealed class " + model.ImplementationTypeName + " : " + model.InterfaceTypeFqn))
        {
            writer.WriteLine("private readonly " + ServiceProviderType + " " + ProviderField + ";");
            writer.WriteLine();

            writer.WriteDocLines(
                "<summary>",
                "Initializes a new instance of the <see cref=\"" + model.ImplementationTypeName + "\"/> class.",
                "</summary>",
                "<param name=\"provider\">The provider every keyed lookup is performed against.</param>");

            using (writer.Block("public " + model.ImplementationTypeName + "(" + ServiceProviderType + " provider)"))
            {
                writer.WriteLine("this." + ProviderField + " = provider;");
            }

            writer.WriteLine();
            writer.WriteDocLines(
                "<inheritdoc />",
                "<remarks>",
                "Delegates straight to <c>GetRequiredKeyedService</c>: no lookup table, no caching, and no",
                "fallback -- whatever it throws for a key nothing is registered under is this method's",
                "contract too.",
                "</remarks>");

            writer.WriteLine(
                "public " + model.ReturnTypeFqn + " " + model.MethodName +
                "(" + model.ParameterTypeFqn + " " + model.ParameterName + ")");

            using (writer.Indent())
            {
                writer.WriteLine(
                    "=> " + KeyedServiceExtensionsType + ".GetRequiredKeyedService<" + model.LookupTypeFqn + ">(" +
                    "this." + ProviderField + ", " + model.ParameterName + ");");
            }
        }
    }
}
