using System.Collections.Immutable;
using System.Text;
using SsalKit.DependencyInjection.Generator.Models;

namespace SsalKit.DependencyInjection.Generator.Emission;

/// <summary>
/// Renders the collected <see cref="ClassRegistrationModel"/>s for an assembly into a single,
/// deterministic C# source file containing one <c>IServiceCollection</c> extension method.
/// </summary>
internal static class ServiceRegistrationEmitter
{
    private const string ServicesParameter = "services";

    public static (string HintName, string Source) Emit(ImmutableArray<ClassRegistrationModel> classes, string? assemblyName)
    {
        var sanitizedName = AssemblyNameSanitizer.ToPascalCaseIdentifier(assemblyName);
        var className = $"{sanitizedName}ServiceCollectionExtensions";
        var methodName = $"Add{sanitizedName}Services";

        // Deterministic output regardless of the order pipeline nodes happened to run in.
        var orderedClasses = classes
            .Sort((a, b) => string.CompareOrdinal(a.ImplementationTypeFqn, b.ImplementationTypeFqn));

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        // TryAdd*/TryAddEnumerable/Replace live in a different namespace than IServiceCollection
        // itself and are not found via global:: qualification on a call-site (extension method
        // invocation syntax is resolved through using directives, not qualified names), so this
        // using is required even though every *type* referenced below is still global::-qualified.
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers every class decorated with <c>[Service]</c> in this assembly with an");
        sb.AppendLine("    /// <see cref=\"global::Microsoft.Extensions.DependencyInjection.IServiceCollection\"/>.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <remarks>Generated by the SsalKit.DependencyInjection source generator. Do not edit by hand.</remarks>");
        sb.Append("    public static class ").Append(className).AppendLine();
        sb.AppendLine("    {");
        sb.Append("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection ")
          .Append(methodName)
          .Append("(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection ")
          .Append(ServicesParameter)
          .AppendLine(")");
        sb.AppendLine("        {");

        foreach (var classModel in orderedClasses)
        {
            foreach (var entry in classModel.Entries)
            {
                WriteRegistration(sb, "            ", classModel.ImplementationTypeFqn, entry);
            }
        }

        sb.Append("            return ").Append(ServicesParameter).AppendLine(";");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return ($"{className}.g.cs", sb.ToString());
    }

    private static void WriteRegistration(StringBuilder sb, string indent, string implementationTypeFqn, RegistrationEntryModel entry)
    {
        var lifetimeName = GetLifetimeName(entry.Lifetime);
        var mode = (WellKnownRegistrationMode)entry.Mode;
        var keyed = entry.Key.HasKey;
        var keyExpression = entry.Key.Expression;

        if (entry.RequiresForwarding)
        {
            // Concrete registration shares a single instance across all forwarded service types.
            // Never reached for an open generic entry: RequiresForwarding is unconditionally false
            // when IsOpenGeneric (see RegistrationEntryModel.RequiresForwarding). Only the
            // self-registration statement (this one) invokes the factory, if any; every forwarded
            // statement below resolves the already-constructed shared instance instead.
            new RegistrationStatement(implementationTypeFqn, implementationTypeFqn, mode, lifetimeName, keyed, keyExpression, Forwarded: false, entry.IsOpenGeneric, entry.Factory)
                .WriteTo(sb, indent);

            foreach (var serviceTypeFqn in entry.ServiceTypeFqns)
            {
                new RegistrationStatement(serviceTypeFqn, implementationTypeFqn, mode, lifetimeName, keyed, keyExpression, Forwarded: true, entry.IsOpenGeneric, FactoryModel.None)
                    .WriteTo(sb, indent);
            }
        }
        else
        {
            foreach (var serviceTypeFqn in entry.ServiceTypeFqns)
            {
                new RegistrationStatement(serviceTypeFqn, implementationTypeFqn, mode, lifetimeName, keyed, keyExpression, Forwarded: false, entry.IsOpenGeneric, entry.Factory)
                    .WriteTo(sb, indent);
            }
        }
    }

    private static string GetLifetimeName(int lifetime) => (WellKnownLifetime)lifetime switch
    {
        WellKnownLifetime.Singleton => "Singleton",
        WellKnownLifetime.Scoped => "Scoped",
        WellKnownLifetime.Transient => "Transient",
        // Unreachable: SSAL008 causes the analyzer to report, and the parser to drop, any entry
        // whose Lifetime is not one of the values above; silently falling back to "Transient" here
        // would otherwise mask an undefined ServiceLifetime value (e.g. from `(ServiceLifetime)42`).
        _ => throw new InvalidOperationException($"Unreachable: '{lifetime}' is not a defined ServiceLifetime value."),
    };

    /// <summary>
    /// Everything needed to render one <c>services.XXX(...)</c> registration statement.
    /// </summary>
    /// <remarks>
    /// Every mode (Add/TryAdd/TryAddEnumerable/Replace), keyed or not, direct or forwarded, reduces
    /// to the same three building blocks: a <em>member name</em> (the lifetime, optionally prefixed
    /// with "Keyed"), an <em>argument list</em> (a generic type-argument list plus call arguments
    /// for a closed registration, or a single call-argument list of <c>typeof(...)</c> expressions
    /// for an open generic one -- see <see cref="IsOpenGeneric"/>), and how that member/argument
    /// pair gets wrapped: Add/TryAdd call it directly as an extension method, TryAddEnumerable/
    /// Replace call it through <c>ServiceDescriptor</c>.
    /// </remarks>
    private readonly record struct RegistrationStatement(
        string ServiceTypeFqn,
        string ImplementationTypeFqn,
        WellKnownRegistrationMode Mode,
        string LifetimeName,
        bool Keyed,
        string? KeyExpression,
        bool Forwarded,
        bool IsOpenGeneric,
        FactoryModel Factory)
    {
        private const string ServiceDescriptorQualifiedName = "global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.";

        private string MemberName => (Keyed ? "Keyed" : string.Empty) + LifetimeName;

        /// <summary>
        /// A forwarded statement, or a direct <c>TryAdd</c>/<c>TryAddKeyed</c> call with a factory,
        /// renders only the service type; every other shape renders both.
        /// </summary>
        /// <remarks>
        /// Unlike <c>Add*</c>/<c>ServiceDescriptor.*</c> (used by Add, TryAddEnumerable, and
        /// Replace), Microsoft.Extensions.DependencyInjection's direct <c>TryAddTransient</c>/
        /// <c>TryAddScoped</c>/<c>TryAddSingleton</c>/<c>TryAddKeyedXxx</c> extension methods have
        /// no <c>&lt;TService, TImplementation&gt;(Func&lt;IServiceProvider, TImplementation&gt;)</c>
        /// (or keyed equivalent) overload at all -- only a single-generic-argument
        /// <c>&lt;TService&gt;(Func&lt;IServiceProvider, TService&gt;)</c> one. The factory method's
        /// return type (the decorated class) is always implicitly convertible to
        /// <c>ServiceTypeFqn</c> (an interface/base type it implements, or itself), so dropping the
        /// second type argument here -- exactly as a forwarded statement already does -- still
        /// type-checks.
        /// </remarks>
        private string GenericArguments => Forwarded || (Mode == WellKnownRegistrationMode.TryAdd && Factory.HasFactory)
            ? $"<{ServiceTypeFqn}>"
            : $"<{ServiceTypeFqn}, {ImplementationTypeFqn}>";

        /// <summary>
        /// The factory invocation expression, e.g. <c>global::Ns.Foo.Create(sp)</c> or
        /// <c>global::Ns.Foo.Create()</c>. Only ever used for a non-forwarded statement (see
        /// <see cref="CallArguments"/>) -- <see cref="Factory"/> is always
        /// <see cref="FactoryModel.None"/> on a forwarded statement.
        /// </summary>
        private string FactoryInvocation => Factory.AcceptsServiceProvider
            ? $"{ImplementationTypeFqn}.{Factory.MethodName}(sp)"
            : $"{ImplementationTypeFqn}.{Factory.MethodName}()";

        /// <summary>
        /// Every combination of keyed/forwarded/factory reduces to one of six call-argument shapes.
        /// A forwarded statement never has a factory (see <see cref="Emit"/>'s callers), so the
        /// <c>Factory</c> component of the switch is a wildcard for the two <c>Forwarded: true</c>
        /// cases -- both are always reached with <see cref="FactoryModel.None"/> in practice, but
        /// nothing here depends on that beyond what <see cref="FactoryInvocation"/> would already
        /// guard against (it is simply never called when <c>Forwarded</c> is <see langword="true"/>).
        /// </summary>
        private string CallArguments => (Keyed, Forwarded, Factory.HasFactory) switch
        {
            (false, false, false) => string.Empty,
            (false, false, true) => $"sp => {FactoryInvocation}",
            (true, false, false) => KeyExpression!,
            (true, false, true) => $"{KeyExpression}, (sp, key) => {FactoryInvocation}",
            (false, true, _) => $"sp => sp.GetRequiredService<{ImplementationTypeFqn}>()",
            (true, true, _) => $"{KeyExpression}, (sp, key) => sp.GetRequiredKeyedService<{ImplementationTypeFqn}>(key)",
        };

        /// <summary>
        /// The Type-based call arguments for an open generic registration: MEDI has no generic-type
        /// -parameter overload that accepts an open (unbound) generic type argument, so both the
        /// service and implementation types are instead passed as <c>typeof(...)</c> values.
        /// <see cref="Forwarded"/> is never <see langword="true"/> here -- forwarding is
        /// unconditionally disabled for an open generic entry (see
        /// <see cref="Models.RegistrationEntryModel.RequiresForwarding"/>) -- so only the
        /// self-registration (service == implementation) and independent-per-service-type shapes
        /// are reachable, both of which always pass both types.
        /// </summary>
        private string OpenGenericCallArguments => Keyed
            ? $"typeof({ServiceTypeFqn}), {KeyExpression}, typeof({ImplementationTypeFqn})"
            : $"typeof({ServiceTypeFqn}), typeof({ImplementationTypeFqn})";

        /// <summary>
        /// The full argument list rendered immediately after the member name: a generic
        /// type-argument list followed by parenthesized call arguments for a closed registration,
        /// or just parenthesized <c>typeof(...)</c> call arguments (no generic type-argument list
        /// at all) for an open generic one.
        /// </summary>
        private string Arguments => IsOpenGeneric
            ? $"({OpenGenericCallArguments})"
            : $"{GenericArguments}({CallArguments})";

        public void WriteTo(StringBuilder sb, string indent)
        {
            sb.Append(indent).Append(ServicesParameter).Append('.');

            // Arguments already includes its own closing ')'; TryAddEnumerable/Replace need one
            // more to close the outer ServiceDescriptor-wrapping call.
            switch (Mode)
            {
                case WellKnownRegistrationMode.Add:
                    sb.Append("Add").Append(MemberName).Append(Arguments).AppendLine(";");
                    break;

                case WellKnownRegistrationMode.TryAdd:
                    sb.Append("TryAdd").Append(MemberName).Append(Arguments).AppendLine(";");
                    break;

                case WellKnownRegistrationMode.TryAddEnumerable:
                    // Keyed + TryAddEnumerable is rejected upstream (SSAL005); never reached here.
                    sb.Append("TryAddEnumerable(").Append(ServiceDescriptorQualifiedName)
                      .Append(MemberName).Append(Arguments).AppendLine(");");
                    break;

                case WellKnownRegistrationMode.Replace:
                    sb.Append("Replace(").Append(ServiceDescriptorQualifiedName)
                      .Append(MemberName).Append(Arguments).AppendLine(");");
                    break;

                default:
                    // Unreachable: SSAL008 causes the analyzer to report, and the parser to drop,
                    // any entry whose Mode is not one of the values above; without this, an
                    // undefined RegistrationMode value (e.g. from `(RegistrationMode)42`) would
                    // silently emit nothing at all instead of failing loudly.
                    throw new InvalidOperationException($"Unreachable: '{(int)Mode}' is not a defined RegistrationMode value.");
            }
        }
    }
}
