using System.Collections.Immutable;
using System.Text;
using SsalKit.DependencyInjection.Generator.Models;

namespace SsalKit.DependencyInjection.Generator.Emission;

/// <summary>
/// Renders the collected <see cref="ClassRegistrationModel"/>s for an assembly into a single,
/// deterministic C# source file containing one <c>IServiceCollection</c> extension method.
/// </summary>
internal static class ServiceRegistrationEmitter
{
    private const string ServicesParameter = "services";

    public static (string HintName, string Source) Emit(ImmutableArray<ClassRegistrationModel> classes, string? assemblyName)
    {
        var sanitizedName = AssemblyNameSanitizer.ToPascalCaseIdentifier(assemblyName);
        var className = $"{sanitizedName}ServiceCollectionExtensions";
        var methodName = $"Add{sanitizedName}Services";

        // Deterministic output regardless of the order pipeline nodes happened to run in.
        var orderedClasses = classes
            .Sort((a, b) => string.CompareOrdinal(a.ImplementationTypeFqn, b.ImplementationTypeFqn));

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        // TryAdd*/TryAddEnumerable/Replace live in a different namespace than IServiceCollection
        // itself and are not found via global:: qualification on a call-site (extension method
        // invocation syntax is resolved through using directives, not qualified names), so this
        // using is required even though every *type* referenced below is still global::-qualified.
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers every class decorated with <c>[Service]</c> in this assembly with an");
        sb.AppendLine("    /// <see cref=\"global::Microsoft.Extensions.DependencyInjection.IServiceCollection\"/>.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <remarks>Generated by the SsalKit.DependencyInjection source generator. Do not edit by hand.</remarks>");
        sb.Append("    public static class ").Append(className).AppendLine();
        sb.AppendLine("    {");
        sb.Append("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection ")
          .Append(methodName)
          .Append("(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection ")
          .Append(ServicesParameter)
          .AppendLine(")");
        sb.AppendLine("        {");

        foreach (var classModel in orderedClasses)
        {
            foreach (var entry in classModel.Entries)
            {
                WriteRegistration(sb, "            ", classModel.ImplementationTypeFqn, entry);
            }
        }

        sb.Append("            return ").Append(ServicesParameter).AppendLine(";");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return ($"{className}.g.cs", sb.ToString());
    }

    private static void WriteRegistration(StringBuilder sb, string indent, string implementationTypeFqn, RegistrationEntryModel entry)
    {
        var lifetimeName = GetLifetimeName(entry.Lifetime);
        var mode = (WellKnownRegistrationMode)entry.Mode;
        var keyed = entry.Key.HasKey;
        var keyExpression = entry.Key.Expression;

        if (entry.RequiresForwarding)
        {
            // Concrete registration shares a single instance across all forwarded service types.
            new RegistrationStatement(implementationTypeFqn, implementationTypeFqn, mode, lifetimeName, keyed, keyExpression, Forwarded: false)
                .WriteTo(sb, indent);

            foreach (var serviceTypeFqn in entry.ServiceTypeFqns)
            {
                new RegistrationStatement(serviceTypeFqn, implementationTypeFqn, mode, lifetimeName, keyed, keyExpression, Forwarded: true)
                    .WriteTo(sb, indent);
            }
        }
        else
        {
            foreach (var serviceTypeFqn in entry.ServiceTypeFqns)
            {
                new RegistrationStatement(serviceTypeFqn, implementationTypeFqn, mode, lifetimeName, keyed, keyExpression, Forwarded: false)
                    .WriteTo(sb, indent);
            }
        }
    }

    private static string GetLifetimeName(int lifetime) => (WellKnownLifetime)lifetime switch
    {
        WellKnownLifetime.Singleton => "Singleton",
        WellKnownLifetime.Scoped => "Scoped",
        _ => "Transient",
    };

    /// <summary>
    /// Everything needed to render one <c>services.XXX(...)</c> registration statement.
    /// </summary>
    /// <remarks>
    /// Every mode (Add/TryAdd/TryAddEnumerable/Replace), keyed or not, direct or forwarded, reduces
    /// to the same three building blocks: a <em>member name</em> (the lifetime, optionally prefixed
    /// with "Keyed"), a <em>generic argument list</em> (service type alone when forwarding to an
    /// already-registered instance, service+implementation type otherwise), and a <em>call argument
    /// list</em> (empty, the key literal, a forwarding factory lambda, or both). The four modes then
    /// only differ in how that member/generics/args triple gets wrapped: Add/TryAdd call it directly
    /// as an extension method, TryAddEnumerable/Replace call it through <c>ServiceDescriptor</c>.
    /// </remarks>
    private readonly record struct RegistrationStatement(
        string ServiceTypeFqn,
        string ImplementationTypeFqn,
        WellKnownRegistrationMode Mode,
        string LifetimeName,
        bool Keyed,
        string? KeyExpression,
        bool Forwarded)
    {
        private const string ServiceDescriptorQualifiedName = "global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.";

        private string MemberName => (Keyed ? "Keyed" : string.Empty) + LifetimeName;

        private string GenericArguments => Forwarded
            ? $"<{ServiceTypeFqn}>"
            : $"<{ServiceTypeFqn}, {ImplementationTypeFqn}>";

        private string CallArguments => (Keyed, Forwarded) switch
        {
            (false, false) => string.Empty,
            (true, false) => KeyExpression!,
            (false, true) => $"sp => sp.GetRequiredService<{ImplementationTypeFqn}>()",
            (true, true) => $"{KeyExpression}, (sp, key) => sp.GetRequiredKeyedService<{ImplementationTypeFqn}>(key)",
        };

        public void WriteTo(StringBuilder sb, string indent)
        {
            sb.Append(indent).Append(ServicesParameter).Append('.');

            switch (Mode)
            {
                case WellKnownRegistrationMode.Add:
                    sb.Append("Add").Append(MemberName).Append(GenericArguments).Append('(').Append(CallArguments).AppendLine(");");
                    break;

                case WellKnownRegistrationMode.TryAdd:
                    sb.Append("TryAdd").Append(MemberName).Append(GenericArguments).Append('(').Append(CallArguments).AppendLine(");");
                    break;

                case WellKnownRegistrationMode.TryAddEnumerable:
                    // Keyed + TryAddEnumerable is rejected upstream (SSAL005); never reached here.
                    sb.Append("TryAddEnumerable(").Append(ServiceDescriptorQualifiedName)
                      .Append(MemberName).Append(GenericArguments).Append('(').Append(CallArguments).AppendLine("));");
                    break;

                case WellKnownRegistrationMode.Replace:
                    sb.Append("Replace(").Append(ServiceDescriptorQualifiedName)
                      .Append(MemberName).Append(GenericArguments).Append('(').Append(CallArguments).AppendLine("));");
                    break;
            }
        }
    }
}
