// <auto-generated/>
// Polyfill required to use C# 9+ `init` accessors and records while targeting netstandard2.0,
// which does not ship this type in its reference assemblies. The C# compiler only needs the
// type to *exist* with this exact name/namespace; the implementation is otherwise unused.
namespace System.Runtime.CompilerServices;

internal static class IsExternalInit
{
}
