using SsalKit.Generators.Toolkit;
using SsalKit.Randomness.Generator.Models;

namespace SsalKit.Randomness.Generator.Emission;

/// <summary>
/// Writes one type's selector-less weighted-picking extension class.
/// </summary>
/// <remarks>
/// <para>
/// Every generated method is a one-line delegation to the selector-based runtime overload: the
/// picking algorithm, the argument validation, and the exception contract all stay in
/// <c>SsalKit.Randomness</c>, so there is exactly one implementation of "correct" to maintain and
/// the generated code cannot drift from it.
/// </para>
/// <para>
/// The output deliberately stays inside a conservative slice of C#: block-scoped namespaces rather
/// than file-scoped, <c>global::</c>-qualified names everywhere, no target-typed <c>new</c>, and no
/// extension-member syntax. It is emitted into the *consumer's* compilation, whose
/// <c>LangVersion</c> the generator does not control.
/// </para>
/// </remarks>
internal static class RandomWeightExtensionsEmitter
{
    private const string RandomSourceType = "global::SsalKit.Randomness.IRandomSource";
    private const string WeightedRandomExtensionsType = "global::SsalKit.Randomness.WeightedRandomExtensions";
    private const string WeightedSamplerType = "global::SsalKit.Randomness.WeightedSampler";
    private const string ReadOnlyListType = "global::System.Collections.Generic.IReadOnlyList";

    public static string Emit(WeightedTypeModel model)
    {
        var writer = new IndentedCodeWriter();
        writer.WriteAutoGeneratedHeader();

        if (model.Namespace.Length == 0)
        {
            WriteExtensionClass(writer, model);
        }
        else
        {
            using (writer.Block("namespace " + model.Namespace))
            {
                WriteExtensionClass(writer, model);
            }
        }

        return writer.ToString();
    }

    private static void WriteExtensionClass(IndentedCodeWriter writer, WeightedTypeModel model)
    {
        var visibility = model.IsPublic ? "public" : "internal";

        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Selector-less weighted-picking extensions for");
        writer.WriteLine("/// <see cref=\"" + model.TypeFqn + "\"/>, generated from its <c>[RandomWeight]</c> member.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("/// <remarks>Generated by the SsalKit.Randomness source generator. Do not edit by hand.</remarks>");

        using (writer.Block(visibility + " static class " + model.ExtensionClassName))
        {
            WritePickWeighted(writer, model);

            if (model.Weight == WeightKind.Integral)
            {
                writer.WriteLine();
                WritePickManyWeighted(writer, model, distinct: false);
                writer.WriteLine();
                WritePickManyWeighted(writer, model, distinct: true);
                writer.WriteLine();
                WriteToWeightedSampler(writer, model);
            }
        }
    }

    private static void WritePickWeighted(IndentedCodeWriter writer, WeightedTypeModel model)
    {
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Returns a single random element of <paramref name=\"items\"/>, selected with probability");
        writer.WriteLine("/// proportional to its <c>" + model.MemberAccess + "</c> value.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("/// <param name=\"items\">The candidate items. Must not be empty.</param>");
        writer.WriteLine("/// <param name=\"source\">The random source to draw from.</param>");
        writer.WriteLine("/// <returns>A weighted-randomly selected element of <paramref name=\"items\"/>.</returns>");
        WriteDelegationRemarks(writer, "PickWeighted");

        writer.WriteLine("public static " + model.TypeFqn + " PickWeighted(");
        using (writer.Indent())
        {
            writer.WriteLine("this " + ReceiverType(model) + " items,");
            writer.WriteLine(RandomSourceType + " source)");
            writer.WriteLine("=> " + WeightedRandomExtensionsType + ".PickWeighted(source, items, " + Selector(model) + ");");
        }
    }

    private static void WritePickManyWeighted(IndentedCodeWriter writer, WeightedTypeModel model, bool distinct)
    {
        var methodName = distinct ? "PickManyWeightedDistinct" : "PickManyWeighted";

        writer.WriteLine("/// <summary>");
        writer.WriteLine(distinct
            ? "/// Draws <paramref name=\"count\"/> distinct random elements of <paramref name=\"items\"/> without"
            : "/// Draws <paramref name=\"count\"/> random elements of <paramref name=\"items\"/> with replacement,");
        writer.WriteLine(distinct
            ? "/// replacement, each selected with probability proportional to its <c>" + model.MemberAccess + "</c> value."
            : "/// each selected with probability proportional to its <c>" + model.MemberAccess + "</c> value.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("/// <param name=\"items\">The candidate items. Must not be empty.</param>");
        writer.WriteLine("/// <param name=\"source\">The random source to draw from.</param>");
        writer.WriteLine("/// <param name=\"count\">The number of elements to draw.</param>");
        writer.WriteLine("/// <returns>An array of <paramref name=\"count\"/> weighted-randomly selected elements.</returns>");
        WriteDelegationRemarks(writer, methodName);

        writer.WriteLine("public static " + model.TypeFqn + "[] " + methodName + "(");
        using (writer.Indent())
        {
            writer.WriteLine("this " + ReceiverType(model) + " items,");
            writer.WriteLine(RandomSourceType + " source,");
            writer.WriteLine("int count)");
            writer.WriteLine("=> " + WeightedRandomExtensionsType + "." + methodName + "(source, items, " + Selector(model) + ", count);");
        }
    }

    private static void WriteToWeightedSampler(IndentedCodeWriter writer, WeightedTypeModel model)
    {
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Builds an immutable, thread-safe alias-table sampler over <paramref name=\"items\"/> and their");
        writer.WriteLine("/// <c>" + model.MemberAccess + "</c> values, for repeated <c>O(1)</c> draws.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("/// <param name=\"items\">The candidate items. Must not be empty.</param>");
        writer.WriteLine("/// <returns>A new sampler; call <c>Pick(source)</c> on it to draw.</returns>");
        writer.WriteLine("/// <remarks>");
        writer.WriteLine("/// <para>");
        writer.WriteLine("/// <b>Build once, draw many.</b> Building the table is <c>O(n)</c> and only the draws are");
        writer.WriteLine("/// <c>O(1)</c>, so calling this inside a draw loop rebuilds the table every iteration and");
        writer.WriteLine("/// negates the reason to use a sampler at all. Build one sampler per weighted table, keep it");
        writer.WriteLine("/// (it is immutable and thread-safe), and draw from it repeatedly; for a single draw, call");
        writer.WriteLine("/// <c>PickWeighted</c> instead.");
        writer.WriteLine("/// </para>");
        writer.WriteLine("/// <para>");
        writer.WriteLine("/// Delegates to <c>SsalKit.Randomness.WeightedRandomExtensions.ToWeightedSampler</c>, which");
        writer.WriteLine("/// defines the validation and exception contract.");
        writer.WriteLine("/// </para>");
        writer.WriteLine("/// </remarks>");

        writer.WriteLine("public static " + WeightedSamplerType + "<" + model.TypeFqn + "> ToWeightedSampler(");
        using (writer.Indent())
        {
            writer.WriteLine("this " + ReceiverType(model) + " items)");
            writer.WriteLine("=> " + WeightedRandomExtensionsType + ".ToWeightedSampler(items, " + Selector(model) + ");");
        }
    }

    private static void WriteDelegationRemarks(IndentedCodeWriter writer, string methodName)
    {
        writer.WriteLine("/// <remarks>");
        writer.WriteLine("/// Delegates to the selector-based");
        writer.WriteLine("/// <c>SsalKit.Randomness.WeightedRandomExtensions." + methodName + "</c> overload, which defines");
        writer.WriteLine("/// the validation and exception contract (empty list, negative weight, zero total weight, and");
        writer.WriteLine("/// overflow behaviour).");
        writer.WriteLine("/// </remarks>");
    }

    private static string ReceiverType(WeightedTypeModel model) => ReadOnlyListType + "<" + model.TypeFqn + ">";

    /// <summary>
    /// The weight selector, always with an explicit cast to the runtime overload's weight type.
    /// The cast is redundant for a <c>long</c>/<c>double</c> member but never wrong, and it removes
    /// any dependence on overload resolution's "better conversion target" tie-break between the
    /// <c>Func&lt;T, long&gt;</c> and <c>Func&lt;T, double&gt;</c> overloads, both of which are
    /// applicable for an integral member.
    /// </summary>
    private static string Selector(WeightedTypeModel model)
    {
        var weightType = model.Weight == WeightKind.Integral ? "long" : "double";
        return "static x => (" + weightType + ")x." + model.MemberAccess;
    }
}
