using SsalKit.Generators.Toolkit;
using SsalKit.Guard.Generator.Models;

namespace SsalKit.Guard.Generator.Emission;

/// <summary>
/// Writes one container's generated part: the mapping table, and the factory and throw helpers for
/// the exceptions declared in this compilation.
/// </summary>
/// <remarks>
/// <para>
/// The lookup is written as a chain of <c>is</c> tests rather than a <c>switch</c> on type patterns.
/// The two compile to the same sequence of type checks, but the <c>is</c> chain is valid in every
/// C# version and reads in exactly the order the registrations are tested -- which is the property
/// this generator exists to guarantee, and the one a reader will want to verify by eye.
/// </para>
/// <para>
/// The output deliberately stays inside a conservative slice of C#: block-scoped namespaces rather
/// than file-scoped, <c>global::</c>-qualified names everywhere, explicit <c>default(T)</c>, and no
/// target-typed <c>new</c>. It is emitted into the *consumer's* compilation, whose
/// <c>LangVersion</c> the generator does not control.
/// </para>
/// </remarks>
internal static class ErrorCodesEmitter
{
    private const string ExceptionType = "global::System.Exception";

    /// <summary>
    /// The mapping methods' parameter type. Nullable on purpose: they document a null reference as
    /// matching nothing, and a non-nullable parameter would make the caller warn (CS8604) for doing
    /// exactly what the documentation promises -- <c>ex.InnerException</c> at a boundary being the
    /// obvious case.
    /// </summary>
    private const string NullableExceptionType = ExceptionType + "?";

    private const string DoesNotReturnAttribute = "global::System.Diagnostics.CodeAnalysis.DoesNotReturn";

    public static string Emit(ErrorCodesContainerModel model)
    {
        var writer = new IndentedCodeWriter();
        writer.WriteAutoGeneratedHeader();

        if (model.Namespace.Length == 0)
        {
            WriteContainingTypes(writer, model, 0);
        }
        else
        {
            using (writer.Block("namespace " + model.Namespace))
            {
                WriteContainingTypes(writer, model, 0);
            }
        }

        return writer.ToString();
    }

    /// <summary>
    /// Re-declares each type containing the container, outermost first, before writing the container
    /// itself. A nested container's generated part has to reproduce the whole nesting chain, and
    /// every type in it therefore has to be <c>partial</c> in the user's own code.
    /// </summary>
    private static void WriteContainingTypes(IndentedCodeWriter writer, ErrorCodesContainerModel model, int index)
    {
        if (index == model.ContainingTypeDeclarations.Length)
        {
            WriteContainer(writer, model);
            return;
        }

        using (writer.Block(model.ContainingTypeDeclarations[index]))
        {
            WriteContainingTypes(writer, model, index + 1);
        }
    }

    private static void WriteContainer(IndentedCodeWriter writer, ErrorCodesContainerModel model)
    {
        writer.WriteDocLines(
            "<summary>",
            "The generated half of the <c>" + model.TCodeDisplayName + "</c> error-code mapping container.",
            "</summary>",
            "<remarks>Generated by the SsalKit.Guard source generator. Do not edit by hand.</remarks>");

        using (writer.Block(model.ContainerDeclaration))
        {
            WriteTryMap(writer, model);
            writer.WriteLine();
            WriteMapOrDefault(writer, model);

            foreach (var helper in model.Helpers)
            {
                writer.WriteLine();
                WriteFactory(writer, helper);
                writer.WriteLine();
                WriteThrowHelper(writer, helper);
            }
        }
    }

    private static void WriteTryMap(IndentedCodeWriter writer, ErrorCodesContainerModel model)
    {
        writer.WriteDocLines(
            "<summary>",
            "Looks up the error code registered for the runtime type of <paramref name=\"exception\"/>.",
            "</summary>",
            "<param name=\"exception\">The exception to map.</param>",
            "<param name=\"code\">",
            "When this method returns <see langword=\"true\"/>, the code registered for the exception's",
            "type; otherwise the default value of <see cref=\"" + model.TCodeFqn + "\"/>.",
            "</param>",
            "<returns>",
            "<see langword=\"true\"/> when a registration matched; otherwise <see langword=\"false\"/>.",
            "</returns>",
            "<remarks>",
            "Registrations are tested most-derived first, so an exception always matches the most",
            "specific registered type rather than whichever base type happens to be written first.",
            "The order is generated from the registered types' inheritance depth and never has to be",
            "maintained by hand. An exception with no registration -- including a null reference --",
            "matches nothing and yields <see langword=\"false\"/>.",
            "</remarks>");

        using (writer.Block(
            model.MapAccessibility + " static bool TryMap(" + NullableExceptionType + " exception, out " + model.TCodeFqn + " code)"))
        {
            foreach (var entry in model.Entries)
            {
                using (writer.Block("if (exception is " + entry.ExceptionFqn + ")"))
                {
                    writer.WriteLine("code = " + entry.CodeExpression + ";");
                    writer.WriteLine("return true;");
                }

                writer.WriteLine();
            }

            writer.WriteLine("code = default(" + model.TCodeFqn + ");");
            writer.WriteLine("return false;");
        }
    }

    private static void WriteMapOrDefault(IndentedCodeWriter writer, ErrorCodesContainerModel model)
    {
        writer.WriteDocLines(
            "<summary>",
            "Looks up the error code registered for the runtime type of <paramref name=\"exception\"/>,",
            "falling back to <paramref name=\"fallback\"/> when no registration matches.",
            "</summary>",
            "<param name=\"exception\">The exception to map.</param>",
            "<param name=\"fallback\">The code to return when no registration matches.</param>",
            "<returns>The registered code, or <paramref name=\"fallback\"/>.</returns>",
            "<remarks>",
            "Shares the matching order of <c>TryMap</c>; the two differ only in how an unmapped",
            "exception is reported. Prefer <c>TryMap</c> where \"unmapped\" has to be handled",
            "differently from any real code -- logging the exception at the boundary, for instance.",
            "</remarks>");

        using (writer.Block(
            model.MapAccessibility + " static " + model.TCodeFqn + " MapOrDefault("
            + NullableExceptionType + " exception, " + model.TCodeFqn + " fallback)"))
        {
            using (writer.Block("if (TryMap(exception, out " + model.TCodeFqn + " code))"))
            {
                writer.WriteLine("return code;");
            }

            writer.WriteLine();
            writer.WriteLine("return fallback;");
        }
    }

    private static void WriteFactory(IndentedCodeWriter writer, ExceptionHelperModel helper)
    {
        writer.WriteDocLines(
            "<summary>",
            "Creates a new <see cref=\"" + helper.ExceptionFqn + "\"/>, which maps to",
            "<c>" + helper.CodeDisplayName + "</c>.",
            "</summary>");
        WriteParameterDocs(writer, helper);
        writer.WriteDocLines(
            "<returns>The new exception, ready to be thrown.</returns>");

        using (writer.Block(
            helper.Accessibility + " static " + helper.ExceptionFqn + " " + helper.FactoryName
            + "(" + ParameterList(helper) + ")"))
        {
            writer.WriteLine("return new " + helper.ExceptionFqn + "(" + ArgumentList(helper) + ");");
        }
    }

    private static void WriteThrowHelper(IndentedCodeWriter writer, ExceptionHelperModel helper)
    {
        writer.WriteDocLines(
            "<summary>",
            "Throws a new <see cref=\"" + helper.ExceptionFqn + "\"/>, which maps to",
            "<c>" + helper.CodeDisplayName + "</c>.",
            "</summary>");
        WriteParameterDocs(writer, helper);
        writer.WriteDocLines(
            "<exception cref=\"" + helper.ExceptionFqn + "\">Always.</exception>",
            "<remarks>",
            "Marked <c>[DoesNotReturn]</c>, so the compiler's nullable flow analysis treats the path",
            "through this call as ended: a value null-checked just before it stays non-null on the",
            "way out, and nothing after it is analysed as reachable.",
            "</remarks>");

        writer.WriteLine("[" + DoesNotReturnAttribute + "]");

        using (writer.Block(
            helper.Accessibility + " static void " + helper.ThrowName + "(" + ParameterList(helper) + ")"))
        {
            writer.WriteLine("throw new " + helper.ExceptionFqn + "(" + ArgumentList(helper) + ");");
        }
    }

    private static void WriteParameterDocs(IndentedCodeWriter writer, ExceptionHelperModel helper)
    {
        if (helper.Constructor == ConstructorShape.Parameterless)
        {
            return;
        }

        if (helper.MessageIsNullable)
        {
            writer.WriteDocLines(
                "<param name=\"message\">",
                "The message that describes the error, or <see langword=\"null\"/> to use the",
                "exception's default message.",
                "</param>");
        }
        else
        {
            writer.WriteDocLines("<param name=\"message\">The message that describes the error.</param>");
        }

        if (helper.Constructor == ConstructorShape.MessageAndInner)
        {
            writer.WriteDocLines(helper.InnerIsNullable
                ? "<param name=\"innerException\">The exception that caused this one, or <see langword=\"null\"/>.</param>"
                : "<param name=\"innerException\">The exception that caused this one.</param>");
        }
    }

    /// <summary>
    /// Mirrors the constructor the helper delegates to, nullability included: a parameter the
    /// exception itself declares as non-nullable stays non-nullable (and therefore required) here,
    /// so the generated signature never promises something the constructor would warn about.
    /// </summary>
    private static string ParameterList(ExceptionHelperModel helper)
    {
        if (helper.Constructor == ConstructorShape.Parameterless)
        {
            return string.Empty;
        }

        var message = helper.MessageIsNullable ? "string? message" : "string message";
        if (helper.Constructor == ConstructorShape.Message)
        {
            return helper.MessageIsNullable ? message + " = null" : message;
        }

        var inner = (helper.InnerIsNullable ? ExceptionType + "? innerException" : ExceptionType + " innerException")
            + (helper.InnerIsNullable ? " = null" : string.Empty);

        // A default may only be given to a trailing run of parameters, so the message keeps its own
        // only when everything after it has one too.
        if (helper.MessageIsNullable && helper.InnerIsNullable)
        {
            message += " = null";
        }

        return message + ", " + inner;
    }

    private static string ArgumentList(ExceptionHelperModel helper) => helper.Constructor switch
    {
        ConstructorShape.Message => "message",
        ConstructorShape.MessageAndInner => "message, innerException",
        _ => string.Empty,
    };
}
