using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using SsalKit.DependencyInjection.Generator.Analysis;
using SsalKit.DependencyInjection.Generator.Tests.TestSupport;
using SsalKit.Generators.Toolkit.Testing;

namespace SsalKit.DependencyInjection.Generator.Tests;

/// <summary>
/// Tests for what the analyzers do with <em>generated</em> code: they analyze and report on it
/// (which is what a <c>[Service]</c> written by another generator, or an assembly attribute MSBuild
/// injected into <c>AssemblyInfo.cs</c>, needs), while leaving this generator's own output alone
/// (which is what keeps them agreeing with the generator about what a convention scan found).
/// </summary>
/// <remarks>
/// A file is generated code, as far as Roslyn is concerned, when its first token carries an
/// <c>&lt;auto-generated/&gt;</c> comment or its path matches one of the well-known generated-file
/// patterns. The test compilations here have no path, so the comment is what marks them -- exactly
/// as it marks every file this and every other source generator emits.
/// </remarks>
public class GeneratedCodeAnalysisTests
{
    private const string AutoGeneratedUsings = """
        // <auto-generated/>
        using System;
        using SsalKit.DependencyInjection;
        using Microsoft.Extensions.DependencyInjection;

        """;

    private const string Usings = """
        using System;
        using SsalKit.DependencyInjection;
        using Microsoft.Extensions.DependencyInjection;

        """;

    /// <summary>
    /// SSAL006 is a per-attribute rule: a registration written by a generator is compiled, and
    /// fails at runtime, exactly like a hand-written one, so it has to be reported the same way.
    /// </summary>
    [Fact]
    public async Task ServiceInGeneratedCode_StillReportsPerAttributeDiagnostics()
    {
        const string source = AutoGeneratedUsings + """
            namespace TestNs;

            [Service(ServiceLifetime.Singleton, Mode = RegistrationMode.TryAddEnumerable)]
            public class SelfRegistered { }
            """;

        var diagnostics = await GeneratorTestSupport.RunAnalyzerAsync(source);

        DiagnosticAssert.Single(diagnostics, "SSAL006", DiagnosticSeverity.Error, exclusive: true);
    }

    /// <summary>
    /// The compilation-end rules have to see generated registrations too, or they draw their
    /// conclusions from a compilation that is missing some of its registrations.
    /// </summary>
    [Fact]
    public async Task ServiceInGeneratedCode_CountsTowardsTheCompilationEndTallies()
    {
        const string source = AutoGeneratedUsings + """
            namespace TestNs;

            public interface IFoo { }

            [Service]
            public class FooA : IFoo { }

            [Service]
            public class FooB : IFoo { }
            """;

        var diagnostics = await GeneratorTestSupport.RunAnalyzerAsync(source);

        Assert.Equal(2, diagnostics.Length);
        Assert.All(diagnostics, diagnostic => Assert.Equal("SSAL015", diagnostic.Id));
    }

    /// <summary>
    /// MSBuild's <c>AssemblyAttribute</c> item writes assembly-level attributes into an
    /// auto-generated <c>AssemblyInfo.cs</c>. The declaration was always read (it is read off the
    /// assembly symbol, not off syntax) and always acted on, but the diagnostics for it were
    /// reported from a syntax node action that never ran there -- so a mistake in such a declaration
    /// was silently ignored.
    /// </summary>
    [Fact]
    public async Task ContractDeclaredInGeneratedCode_IsStillDiagnosed()
    {
        const string source = AutoGeneratedUsings + """
            [assembly: RegisterImplementationsOf(typeof(TestNs.NotAnInterface))]

            namespace TestNs;

            public class NotAnInterface { }
            """;

        var diagnostics = await GeneratorTestSupport.RunAnalyzerAsync(source);

        DiagnosticAssert.Single(diagnostics, "SSAL021", DiagnosticSeverity.Error, exclusive: true);
    }

    /// <summary>
    /// The SSAL022 false positive this pairing produced, in the shape it actually occurs in: the
    /// contract is declared in ordinary source (so the warning about it is reported), while the only
    /// class implementing it lives in a generated file. <c>ConventionScanner</c> walks the assembly's
    /// symbols and registers that class like any other, but the analyzer's symbol action skipped it,
    /// so the contract was reported as matching nothing even though the generator had registered an
    /// implementation for it.
    /// </summary>
    [Fact]
    public async Task ImplementationInAGeneratedFile_SatisfiesAContractDeclaredInOrdinarySource()
    {
        const string ordinary = Usings + """
            [assembly: RegisterImplementationsOf(typeof(TestNs.IStartupTask))]

            namespace TestNs;

            public interface IStartupTask { }
            """;

        const string generated = """
            // <auto-generated/>
            namespace TestNs
            {
                public sealed class WarmCaches : IStartupTask { }
            }
            """;

        Assert.Empty(await RunAnalyzersOnAsync(ordinary, generated));

        // Control: with the generated file's class gone, the contract really does match nothing, so
        // the warning must still be reported. This is what proves the test above is not passing
        // simply because the whole rule went quiet.
        DiagnosticAssert.Single(
            await RunAnalyzersOnAsync(ordinary, "// <auto-generated/>"),
            "SSAL022",
            DiagnosticSeverity.Warning,
            exclusive: true);
    }

    /// <summary>
    /// The reverse asymmetry, and the reason generated code cannot simply be trusted wholesale: a
    /// source generator runs against the compilation as it was <em>before</em> any generator ran, so
    /// <c>ConventionScanner</c> can never see this generator's own factory implementations. An
    /// analyzer running on the final compilation can, and counting them would let a contract that
    /// the generator registered nothing for look satisfied.
    /// </summary>
    [Fact]
    public async Task ThisGeneratorsOwnOutput_IsNotCountedAsAConventionMatch()
    {
        const string source = Usings + """
            [assembly: RegisterImplementationsOf(typeof(TestNs.IStartupTask))]

            namespace TestNs
            {
                public interface IStartupTask { }
            }

            namespace SsalKit.DependencyInjection.Generated.TestNs
            {
                internal sealed class IStartupTaskImplementation : global::TestNs.IStartupTask { }
            }
            """;

        var diagnostics = await GeneratorTestSupport.RunAnalyzerAsync(source);

        DiagnosticAssert.Single(diagnostics, "SSAL022", DiagnosticSeverity.Warning, exclusive: true);
    }

    /// <summary>
    /// The exclusion is a namespace-boundary rule, not a prefix match: a consumer namespace that
    /// merely starts with the same characters is ordinary code.
    /// </summary>
    [Fact]
    public async Task ANamespaceMerelyPrefixedByTheReservedRoot_IsOrdinaryCode()
    {
        const string source = Usings + """
            [assembly: RegisterImplementationsOf(typeof(TestNs.IStartupTask))]

            namespace TestNs
            {
                public interface IStartupTask { }
            }

            namespace SsalKit.DependencyInjection.GeneratedThings
            {
                public sealed class WarmCaches : global::TestNs.IStartupTask { }
            }
            """;

        var diagnostics = await GeneratorTestSupport.RunAnalyzerAsync(source);

        Assert.Empty(diagnostics);
    }

    /// <summary>
    /// The same exclusion applies to <c>[Service]</c> and <c>[ServiceFactory]</c>: nothing this
    /// generator emits is a consumer declaration, so no rule of any of the three analyzers may fire
    /// on one.
    /// </summary>
    [Fact]
    public async Task ThisGeneratorsOwnOutput_IsNeverReportedOn()
    {
        const string source = Usings + """
            namespace SsalKit.DependencyInjection.Generated.TestNs
            {
                // Shapes that would be SSAL001 and SSAL017 respectively in consumer code.
                [Service]
                internal abstract class GeneratedAbstract { }

                [ServiceFactory]
                internal interface IGeneratedEmptyFactory { }
            }
            """;

        var diagnostics = await GeneratorTestSupport.RunAnalyzerAsync(source);

        Assert.Empty(diagnostics);
    }

    /// <summary>
    /// Runs all three analyzers over a compilation of more than one file, which
    /// <see cref="GeneratorTestSupport.RunAnalyzerAsync"/> (one source string) cannot express -- and
    /// which is the only way to have ordinary and generated code in the same compilation.
    /// </summary>
    private static async Task<ImmutableArray<Diagnostic>> RunAnalyzersOnAsync(params string[] sources)
    {
        var compilation = GeneratorTest
            .CreateCompilation(sources[0], GeneratorTestSupport.Options)
            .AddSyntaxTrees(sources.Skip(1).Select(source => CSharpSyntaxTree.ParseText(source)));

        var diagnostics = await compilation
            .WithAnalyzers([new ServiceAttributeAnalyzer(), new ServiceFactoryAnalyzer(), new RegisterImplementationsOfAnalyzer()])
            .GetAllDiagnosticsAsync();

        return [.. diagnostics.Where(diagnostic => diagnostic.Id.StartsWith("SSAL", StringComparison.Ordinal))];
    }
}
