<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Verify.Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SsalKit.DependencyInjection.Generator\SsalKit.DependencyInjection.Generator.csproj" />
    <ProjectReference Include="..\..\src\SsalKit.DependencyInjection\SsalKit.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\src\SsalKit.Generators.Toolkit.Testing\SsalKit.Generators.Toolkit.Testing.csproj" />
  </ItemGroup>

</Project>
