using System.Globalization;
using System.Linq;
using System.Text;
using SsalKit.Generators.Toolkit;
using SsalKit.StableHashing.Generator.Models;

namespace SsalKit.StableHashing.Generator.Emission;

/// <summary>
/// Writes one contract type's <c>ComputeStableHash</c>/<c>AppendStableHash</c> extension class
/// (design §3.4).
/// </summary>
/// <remarks>
/// <para>
/// The output deliberately stays inside a conservative slice of C#: block-scoped namespaces rather
/// than file-scoped, <c>global::</c>-qualified names everywhere, indexed <c>for</c> loops instead
/// of <c>foreach</c>/LINQ, and no target-typed <c>new</c> -- it is emitted into the *consumer's*
/// compilation, whose <c>LangVersion</c> the generator does not control (mirrors
/// <c>SsalKit.Randomness.Generator</c>'s <c>RandomWeightExtensionsEmitter</c>).
/// </para>
/// <para>
/// Every member value is written by <see cref="EmitValue"/>, which recurses one <see cref="TypeShape"/>
/// layer at a time: a <see cref="TypeShapeKind.NullableValue"/>/<see cref="TypeShapeKind.NullableReference"/>
/// wrapper becomes a null marker plus a conditional block around its <c>Inner</c> shape; a
/// <see cref="TypeShapeKind.Collection"/> becomes a count plus an index loop around its
/// <c>Element</c> shape. Because each member's shape is a single linear chain (never branching),
/// and the loop-variable suffix passed down is the recursion depth, every index variable a given
/// member's emission introduces is guaranteed distinct from every other one it introduces --
/// siblings across different members are safe too, since each member's whole block is closed
/// before the next one's is opened.
/// </para>
/// </remarks>
internal static class StableHashEmitter
{
    public static string Emit(ContractModel model)
    {
        var writer = new IndentedCodeWriter();
        writer.WriteAutoGeneratedHeader();

        if (model.Namespace.Length == 0)
        {
            WriteExtensionClass(writer, model);
        }
        else
        {
            using (writer.Block("namespace " + model.Namespace))
            {
                WriteExtensionClass(writer, model);
            }
        }

        return writer.ToString();
    }

    private static void WriteExtensionClass(IndentedCodeWriter writer, ContractModel model)
    {
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Stable-hash encoding for <see cref=\"" + model.TypeFqn + "\"/>, generated from its");
        writer.WriteLine("/// <c>[StableHashContract]</c> and <c>[StableHashMember]</c> attributes.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("/// <remarks>Generated by the SsalKit.StableHashing source generator. Do not edit by hand.</remarks>");

        using (writer.Block("public static class " + model.ExtensionClassName))
        {
            WriteComputeStableHash(writer, model);
            writer.WriteLine();
            WriteAppendStableHash(writer, model);
        }
    }

    private static void WriteComputeStableHash(IndentedCodeWriter writer, ContractModel model)
    {
        writer.WriteLine("/// <summary>Computes the stable hash of <paramref name=\"value\"/>.</summary>");
        writer.WriteLine("/// <param name=\"value\">The value to hash.</param>");
        writer.WriteLine("/// <returns>The computed hash.</returns>");

        if (model.IsClassContract)
        {
            writer.WriteLine("/// <exception cref=\"global::System.ArgumentNullException\"><paramref name=\"value\"/> is null.</exception>");
        }

        using (writer.Block(
            "public static global::SsalKit.StableHashing.StableHash64 ComputeStableHash(this " + model.TypeFqn + " value)"))
        {
            if (model.IsClassContract)
            {
                writer.WriteLine("if (value is null)");
                using (writer.Indent())
                {
                    writer.WriteLine("throw new global::System.ArgumentNullException(nameof(value));");
                }

                writer.WriteLine();
            }

            writer.WriteLine("var writer = global::SsalKit.StableHashing.StableHashWriter.Create();");
            writer.WriteLine("value.AppendStableHash(ref writer);");
            writer.WriteLine("return writer.Finish();");
        }
    }

    private static void WriteAppendStableHash(IndentedCodeWriter writer, ContractModel model)
    {
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Appends <paramref name=\"value\"/>'s encoding -- including this contract's own header --");
        writer.WriteLine("/// to <paramref name=\"writer\"/>. Used both by <c>ComputeStableHash</c> and by any other");
        writer.WriteLine("/// contract that holds a <see cref=\"" + model.TypeFqn + "\"/> as a nested member.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("/// <param name=\"value\">The value to encode.</param>");
        writer.WriteLine("/// <param name=\"writer\">The writer to append to.</param>");

        var signature = "public static void AppendStableHash(this " + model.TypeFqn
            + " value, ref global::SsalKit.StableHashing.StableHashWriter writer)";

        using (writer.Block(signature))
        {
            writer.WriteLine(
                "writer.AppendContractHeader(" + QuoteString(model.ContractName ?? string.Empty) + ", "
                + model.Version.ToString(CultureInfo.InvariantCulture) + ");");

            foreach (var member in model.Members.OrderBy(static m => m.Id))
            {
                writer.WriteLine();
                writer.WriteLine("writer.AppendMemberId(" + member.Id.ToString(CultureInfo.InvariantCulture) + ");");
                EmitValue(writer, member.Shape, member.AccessExpression, 0);
            }
        }
    }

    private static void EmitValue(IndentedCodeWriter writer, TypeShape shape, string valueExpr, int depth)
    {
        switch (shape.Kind)
        {
            case TypeShapeKind.Primitive:
                writer.WriteLine("writer.Append" + shape.AppendMethodSuffix + "(" + valueExpr + ");");
                break;

            case TypeShapeKind.Enum:
                writer.WriteLine(
                    "writer.Append" + shape.AppendMethodSuffix + "((" + shape.EnumUnderlyingTypeKeyword + ")" + valueExpr + ");");
                break;

            case TypeShapeKind.Contract:
                writer.WriteLine(shape.ContractExtensionsFqn + ".AppendStableHash(" + valueExpr + ", ref writer);");
                break;

            case TypeShapeKind.NullableValue:
                writer.WriteLine("writer.AppendNullMarker((" + valueExpr + ").HasValue);");
                using (writer.Block("if ((" + valueExpr + ").HasValue)"))
                {
                    EmitValue(writer, shape.Inner!, "(" + valueExpr + ").Value", depth + 1);
                }

                break;

            case TypeShapeKind.NullableReference:
                writer.WriteLine("writer.AppendNullMarker((" + valueExpr + ") != null);");
                using (writer.Block("if ((" + valueExpr + ") != null)"))
                {
                    // Deliberately not wrapped in an extra "(...)" before the "!": a parenthesized
                    // simple/qualified name immediately followed by a token that can start a
                    // unary-expression (like "!") is grammatically ambiguous with a cast in C#, and
                    // the compiler resolves that ambiguity *as* a cast -- "(value.Foo)!" is parsed
                    // as "cast the following expression to type 'value.Foo'", not as "value.Foo,
                    // null-forgiven". Applying "!" directly to the unparenthesized expression avoids
                    // the ambiguity entirely: postfix operators (member access, indexing, "!") chain
                    // left-associatively without needing parentheses.
                    EmitValue(writer, shape.Inner!, valueExpr + "!", depth + 1);
                }

                break;

            case TypeShapeKind.Collection:
                EmitCollection(writer, shape, valueExpr, depth);
                break;
        }
    }

    private static void EmitCollection(IndentedCodeWriter writer, TypeShape shape, string valueExpr, int depth)
    {
        var indexVar = "i" + depth.ToString(CultureInfo.InvariantCulture);

        if (shape.Form == CollectionForm.ImmutableArray)
        {
            writer.WriteLine(
                "writer.AppendCount((" + valueExpr + ").IsDefault ? 0 : (" + valueExpr + ").Length);");

            using (writer.Block("if (!(" + valueExpr + ").IsDefault)"))
            {
                using (writer.Block(
                    "for (int " + indexVar + " = 0; " + indexVar + " < (" + valueExpr + ").Length; " + indexVar + "++)"))
                {
                    EmitValue(writer, shape.Element!, "(" + valueExpr + ")[" + indexVar + "]", depth + 1);
                }
            }

            return;
        }

        var countProperty = shape.Form == CollectionForm.Array ? "Length" : "Count";

        writer.WriteLine("writer.AppendCount((" + valueExpr + ")." + countProperty + ");");

        using (writer.Block(
            "for (int " + indexVar + " = 0; " + indexVar + " < (" + valueExpr + ")." + countProperty + "; " + indexVar + "++)"))
        {
            EmitValue(writer, shape.Element!, "(" + valueExpr + ")[" + indexVar + "]", depth + 1);
        }
    }

    /// <summary>Renders <paramref name="value"/> as a C# string literal, escaping it for safety.</summary>
    private static string QuoteString(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');

        foreach (var ch in value)
        {
            switch (ch)
            {
                case '"':
                    builder.Append("\\\"");
                    break;
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '\n':
                    builder.Append("\\n");
                    break;
                case '\r':
                    builder.Append("\\r");
                    break;
                case '\t':
                    builder.Append("\\t");
                    break;
                case '\0':
                    builder.Append("\\0");
                    break;
                default:
                    if (char.IsControl(ch))
                    {
                        builder.Append("\\u").Append(((int)ch).ToString("x4", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        builder.Append(ch);
                    }

                    break;
            }
        }

        builder.Append('"');
        return builder.ToString();
    }
}
