using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using SsalKit.Generators.Toolkit;
using SsalKit.StableHashing.Generator.Models;

namespace SsalKit.StableHashing.Generator.Emission;

/// <summary>
/// Writes one contract type's <c>ComputeStableHash</c>/<c>AppendStableHash</c> extension class
/// (design §3.4).
/// </summary>
/// <remarks>
/// <para>
/// The output deliberately stays inside a conservative slice of C#: block-scoped namespaces rather
/// than file-scoped, <c>global::</c>-qualified names everywhere, indexed <c>for</c> loops instead
/// of <c>foreach</c>/LINQ, and no target-typed <c>new</c> -- it is emitted into the *consumer's*
/// compilation, whose <c>LangVersion</c> the generator does not control (mirrors
/// <c>SsalKit.Randomness.Generator</c>'s <c>RandomWeightExtensionsEmitter</c>).
/// </para>
/// <para>
/// <b>Every <c>[StableHashMember]</c> access is read exactly once.</b> <see cref="WriteAppendStableHash"/>
/// captures each member's access expression into a local (<c>var m{id} = value.Foo;</c>) before
/// touching it at all, and every recursive step below that -- unwrapping a
/// <see cref="TypeShapeKind.NullableValue"/>/<see cref="TypeShapeKind.NullableReference"/> layer,
/// or a <see cref="TypeShapeKind.Collection"/>'s count and each element -- likewise captures
/// whatever it is about to read more than once into its own local first, and reads only that local
/// afterwards. This matters because the value being encoded is always the *result of a member's
/// getter* (or an indexer, for a collection element): unlike a plain field, nothing guarantees a
/// getter is side-effect-free or returns the same value on every call, so evaluating it more than
/// once per logical value -- once for a null-marker check, again for the guarded value, again for
/// a loop bound -- would be observably wrong, not just wasteful. Every local introduced this way is
/// named from the member's own id (which SSALH001 already guarantees is unique within the
/// contract) plus the recursion depth plus a one-letter role tag, which makes every name globally
/// unique within the method without needing block-scoping to prevent collisions between sibling
/// members or nested layers.
/// </para>
/// <para>
/// <b>Nested-contract calls resolve through the final, disambiguated class name.</b> A
/// <see cref="TypeShapeKind.Contract"/> shape carries the referenced type's own
/// <see cref="TypeShape.ContractTypeFqn"/> (a fully qualified type name, always unique) rather than
/// a precomputed extension-class name: two different types can flatten to the same tentative class
/// name (design's <c>Outer.Inner</c> vs. top-level <c>Outer_Inner</c> example), and only after
/// <c>ContractNameGrouper</c> has seen every contract in the compilation is it known which one, if
/// either, needed a numeric suffix. <see cref="Emit"/> is handed the resulting
/// type-FQN-to-final-extensions-FQN table and looks up every <see cref="TypeShapeKind.Contract"/>
/// reference through it, falling back to the shape's tentative <see cref="TypeShape.ContractExtensionsFqn"/>
/// only if the referenced type is missing from the table entirely (it has unrelated errors of its
/// own and was never emitted -- calling into it would fail to compile regardless of which name is
/// used).
/// </para>
/// </remarks>
internal static class StableHashEmitter
{
    public static string Emit(ContractModel model, IReadOnlyDictionary<string, string> extensionsFqnByTypeFqn)
    {
        var writer = new IndentedCodeWriter();
        writer.WriteAutoGeneratedHeader();

        if (model.Namespace.Length == 0)
        {
            WriteExtensionClass(writer, model, extensionsFqnByTypeFqn);
        }
        else
        {
            using (writer.Block("namespace " + model.Namespace))
            {
                WriteExtensionClass(writer, model, extensionsFqnByTypeFqn);
            }
        }

        return writer.ToString();
    }

    private static void WriteExtensionClass(
        IndentedCodeWriter writer, ContractModel model, IReadOnlyDictionary<string, string> extensionsFqnByTypeFqn)
    {
        var visibility = model.IsPublic ? "public" : "internal";

        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Stable-hash encoding for <see cref=\"" + model.TypeFqn + "\"/>, generated from its");
        writer.WriteLine("/// <c>[StableHashContract]</c> and <c>[StableHashMember]</c> attributes.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("/// <remarks>Generated by the SsalKit.StableHashing source generator. Do not edit by hand.</remarks>");

        using (writer.Block(visibility + " static class " + model.ExtensionClassName))
        {
            WriteComputeStableHash(writer, model, visibility);
            writer.WriteLine();
            WriteAppendStableHash(writer, model, visibility, extensionsFqnByTypeFqn);
        }
    }

    private static void WriteComputeStableHash(IndentedCodeWriter writer, ContractModel model, string visibility)
    {
        writer.WriteLine("/// <summary>Computes the stable hash of <paramref name=\"value\"/>.</summary>");
        writer.WriteLine("/// <param name=\"value\">The value to hash.</param>");
        writer.WriteLine("/// <returns>The computed hash.</returns>");

        if (model.IsClassContract)
        {
            writer.WriteLine("/// <exception cref=\"global::System.ArgumentNullException\"><paramref name=\"value\"/> is null.</exception>");
        }

        using (writer.Block(
            visibility + " static global::SsalKit.StableHashing.StableHash64 ComputeStableHash(this " + model.TypeFqn + " value)"))
        {
            if (model.IsClassContract)
            {
                writer.WriteLine("if (value is null)");
                using (writer.Indent())
                {
                    writer.WriteLine("throw new global::System.ArgumentNullException(nameof(value));");
                }

                writer.WriteLine();
            }

            writer.WriteLine("var writer = global::SsalKit.StableHashing.StableHashWriter.Create();");
            writer.WriteLine("value.AppendStableHash(ref writer);");
            writer.WriteLine("return writer.Finish();");
        }
    }

    private static void WriteAppendStableHash(
        IndentedCodeWriter writer, ContractModel model, string visibility, IReadOnlyDictionary<string, string> extensionsFqnByTypeFqn)
    {
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Appends <paramref name=\"value\"/>'s encoding -- including this contract's own header --");
        writer.WriteLine("/// to <paramref name=\"writer\"/>. Used both by <c>ComputeStableHash</c> and by any other");
        writer.WriteLine("/// contract that holds a <see cref=\"" + model.TypeFqn + "\"/> as a nested member.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("/// <param name=\"value\">The value to encode.</param>");
        writer.WriteLine("/// <param name=\"writer\">The writer to append to.</param>");

        var signature = visibility + " static void AppendStableHash(this " + model.TypeFqn
            + " value, ref global::SsalKit.StableHashing.StableHashWriter writer)";

        using (writer.Block(signature))
        {
            writer.WriteLine(
                "writer.AppendContractHeader(" + QuoteString(model.ContractName ?? string.Empty) + ", "
                + model.Version.ToString(CultureInfo.InvariantCulture) + ");");

            foreach (var member in model.Members.OrderBy(static m => m.Id))
            {
                var memberPrefix = "m" + member.Id.ToString(CultureInfo.InvariantCulture);

                writer.WriteLine();
                writer.WriteLine("writer.AppendMemberId(" + member.Id.ToString(CultureInfo.InvariantCulture) + ");");
                writer.WriteLine("var " + memberPrefix + " = " + member.AccessExpression + ";");
                EmitValue(writer, member.Shape, memberPrefix, memberPrefix, 0, extensionsFqnByTypeFqn);
            }
        }
    }

    /// <summary>
    /// Writes the code that encodes one already-safe-to-reread value (<paramref name="valueExpr"/>
    /// -- always either a local variable name or a null-forgiven/`.Value`-projected local, never a
    /// raw member/indexer access) according to <paramref name="shape"/>.
    /// </summary>
    /// <param name="memberPrefix">
    /// The owning member's local-name prefix (<c>"m" + id</c>), carried unchanged through the whole
    /// recursion so every local this call (or one nested inside it) introduces stays within that
    /// member's own globally-unique naming subspace.
    /// </param>
    /// <param name="depth">
    /// How many <see cref="TypeShapeKind.NullableValue"/>/<see cref="TypeShapeKind.NullableReference"/>/
    /// <see cref="TypeShapeKind.Collection"/> layers have been unwrapped so far, appended to
    /// <paramref name="memberPrefix"/> to keep locals introduced at different layers distinct.
    /// </param>
    private static void EmitValue(
        IndentedCodeWriter writer,
        TypeShape shape,
        string valueExpr,
        string memberPrefix,
        int depth,
        IReadOnlyDictionary<string, string> extensionsFqnByTypeFqn)
    {
        switch (shape.Kind)
        {
            case TypeShapeKind.Primitive:
                writer.WriteLine("writer.Append" + shape.AppendMethodSuffix + "(" + valueExpr + ");");
                break;

            case TypeShapeKind.Enum:
                writer.WriteLine(
                    "writer.Append" + shape.AppendMethodSuffix + "((" + shape.EnumUnderlyingTypeKeyword + ")" + valueExpr + ");");
                break;

            case TypeShapeKind.Contract:
                var extensionsFqn = shape.ContractTypeFqn is not null
                    && extensionsFqnByTypeFqn.TryGetValue(shape.ContractTypeFqn, out var resolved)
                        ? resolved
                        : shape.ContractExtensionsFqn;
                writer.WriteLine(extensionsFqn + ".AppendStableHash(" + valueExpr + ", ref writer);");
                break;

            case TypeShapeKind.NullableValue:
            {
                var local = memberPrefix + "_" + depth.ToString(CultureInfo.InvariantCulture);
                writer.WriteLine("var " + local + " = " + valueExpr + ";");
                writer.WriteLine("writer.AppendNullMarker(" + local + ".HasValue);");
                using (writer.Block("if (" + local + ".HasValue)"))
                {
                    EmitValue(writer, shape.Inner!, local + ".Value", memberPrefix, depth + 1, extensionsFqnByTypeFqn);
                }

                break;
            }

            case TypeShapeKind.NullableReference:
            {
                var local = memberPrefix + "_" + depth.ToString(CultureInfo.InvariantCulture);
                writer.WriteLine("var " + local + " = " + valueExpr + ";");
                writer.WriteLine("writer.AppendNullMarker(" + local + " != null);");
                using (writer.Block("if (" + local + " != null)"))
                {
                    // "!" applied directly to the bare local, never wrapped in "(...)": a
                    // parenthesized simple name immediately followed by a token that can start a
                    // unary-expression (like "!") is grammatically ambiguous with a cast in C#, and
                    // the compiler resolves that ambiguity *as* a cast -- "(m1_0)!" would parse as
                    // "cast the following expression to type 'm1_0'". A bare "m1_0!" has no such
                    // ambiguity (a cast must start with "(").
                    EmitValue(writer, shape.Inner!, local + "!", memberPrefix, depth + 1, extensionsFqnByTypeFqn);
                }

                break;
            }

            case TypeShapeKind.Collection:
                EmitCollection(writer, shape, valueExpr, memberPrefix, depth, extensionsFqnByTypeFqn);
                break;
        }
    }

    private static void EmitCollection(
        IndentedCodeWriter writer,
        TypeShape shape,
        string valueExpr,
        string memberPrefix,
        int depth,
        IReadOnlyDictionary<string, string> extensionsFqnByTypeFqn)
    {
        var depthSuffix = depth.ToString(CultureInfo.InvariantCulture);
        var collectionLocal = memberPrefix + "_" + depthSuffix + "c";
        var countLocal = memberPrefix + "_" + depthSuffix + "n";
        var indexVar = memberPrefix + "_" + depthSuffix + "i";
        var elementLocal = memberPrefix + "_" + depthSuffix + "e";

        writer.WriteLine("var " + collectionLocal + " = " + valueExpr + ";");

        if (shape.Form == CollectionForm.ImmutableArray)
        {
            writer.WriteLine(
                "var " + countLocal + " = " + collectionLocal + ".IsDefault ? 0 : " + collectionLocal + ".Length;");
            writer.WriteLine("writer.AppendCount(" + countLocal + ");");

            using (writer.Block("if (!" + collectionLocal + ".IsDefault)"))
            {
                using (writer.Block(
                    "for (int " + indexVar + " = 0; " + indexVar + " < " + countLocal + "; " + indexVar + "++)"))
                {
                    writer.WriteLine("var " + elementLocal + " = " + collectionLocal + "[" + indexVar + "];");
                    EmitValue(writer, shape.Element!, elementLocal, memberPrefix, depth + 1, extensionsFqnByTypeFqn);
                }
            }

            return;
        }

        var countProperty = shape.Form == CollectionForm.Array ? "Length" : "Count";

        writer.WriteLine("var " + countLocal + " = " + collectionLocal + "." + countProperty + ";");
        writer.WriteLine("writer.AppendCount(" + countLocal + ");");

        using (writer.Block("for (int " + indexVar + " = 0; " + indexVar + " < " + countLocal + "; " + indexVar + "++)"))
        {
            writer.WriteLine("var " + elementLocal + " = " + collectionLocal + "[" + indexVar + "];");
            EmitValue(writer, shape.Element!, elementLocal, memberPrefix, depth + 1, extensionsFqnByTypeFqn);
        }
    }

    /// <summary>Renders <paramref name="value"/> as a C# string literal, escaping it for safety.</summary>
    private static string QuoteString(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');

        foreach (var ch in value)
        {
            switch (ch)
            {
                case '"':
                    builder.Append("\\\"");
                    break;
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '\n':
                    builder.Append("\\n");
                    break;
                case '\r':
                    builder.Append("\\r");
                    break;
                case '\t':
                    builder.Append("\\t");
                    break;
                case '\0':
                    builder.Append("\\0");
                    break;
                default:
                    if (char.IsControl(ch))
                    {
                        builder.Append("\\u").Append(((int)ch).ToString("x4", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        builder.Append(ch);
                    }

                    break;
            }
        }

        builder.Append('"');
        return builder.ToString();
    }
}
