// <auto-generated/>
#pragma warning disable
#nullable enable

using Microsoft.CodeAnalysis;

namespace SsalKit.Generators.Toolkit;

/// <summary>
/// Resolves the source location to report a diagnostic about an attribute application on.
/// </summary>
internal static class AttributeLocations
{
    /// <summary>
    /// Returns the location of the attribute application itself -- the token the user wrote and can
    /// edit -- falling back to the decorated symbol, and finally to <see cref="Location.None"/>.
    /// </summary>
    /// <remarks>
    /// <see cref="AttributeData.ApplicationSyntaxReference"/> is <see langword="null"/> whenever the
    /// attribute did not come from source (it was read from metadata, or synthesized), and a symbol
    /// that is itself not from source (a constructed or otherwise synthesized symbol) has no
    /// locations at all -- hence the second fallback. Reporting with <see cref="Location.None"/> is
    /// accepted by <see cref="Diagnostic.Create(DiagnosticDescriptor, Location?, object?[])"/> and
    /// surfaces the diagnostic without a file position, which is strictly better than dropping it.
    /// </remarks>
    /// <param name="attributeData">The attribute application to locate.</param>
    /// <param name="fallbackSymbol">The decorated symbol, used when the attribute has no syntax.</param>
    /// <returns>The best available location, never <see langword="null"/>.</returns>
    public static Location GetLocation(AttributeData attributeData, ISymbol fallbackSymbol)
    {
        var syntaxReference = attributeData.ApplicationSyntaxReference;
        if (syntaxReference is not null)
        {
            return syntaxReference.GetSyntax().GetLocation();
        }

        return fallbackSymbol.Locations.Length > 0 ? fallbackSymbol.Locations[0] : Location.None;
    }
}
