// <auto-generated/>
#pragma warning disable
#nullable enable

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;

namespace SsalKit.Generators.Toolkit;

/// <summary>
/// Helpers for turning arbitrary text into valid C# identifiers, and for escaping identifiers
/// that collide with a reserved keyword.
/// </summary>
internal static class CSharpNaming
{
    private static readonly HashSet<string> ReservedKeywords = new HashSet<string>(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
        "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw",
        "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using",
        "virtual", "void", "volatile", "while",
    };

    /// <summary>
    /// Converts <paramref name="text"/> into a PascalCase identifier fragment by upper-casing the
    /// first letter of each run of letters/digits separated by non-alphanumeric characters, e.g.
    /// <c>"SsalKit.Sample"</c> becomes <c>"SsalKitSample"</c>.
    /// </summary>
    /// <param name="text">The source text. May be <see langword="null"/> or empty.</param>
    /// <param name="fallback">
    /// The value returned when <paramref name="text"/> is <see langword="null"/>, empty, or
    /// contains no letters or digits at all.
    /// </param>
    /// <returns>
    /// A valid leading fragment for a C# identifier. If the resulting fragment would start with
    /// a digit, an underscore is prepended so the overall result remains a valid identifier start.
    /// </returns>
    public static string ToPascalCaseIdentifier(string? text, string fallback = "Identifier") =>
        BuildPascalCore(text) ?? fallback;

    /// <summary>
    /// Converts <paramref name="text"/> into a camelCase identifier fragment by first applying
    /// the same segmentation rules as <see cref="ToPascalCaseIdentifier"/> and then lower-casing
    /// the leading run of upper-case letters. A leading run of two or more upper-case letters is
    /// lowered up to, but not including, the last letter of the run whenever that last letter
    /// begins a new word (e.g. <c>"IOService"</c> becomes <c>"ioService"</c>); a single leading
    /// upper-case letter is always lowered (e.g. <c>"Service"</c> becomes <c>"service"</c>).
    /// </summary>
    /// <param name="text">The source text. May be <see langword="null"/> or empty.</param>
    /// <param name="fallback">
    /// The value returned when <paramref name="text"/> is <see langword="null"/>, empty, or
    /// contains no letters or digits at all.
    /// </param>
    /// <returns>A valid leading fragment for a C# identifier, in camelCase.</returns>
    /// <remarks>
    /// <b>The result may be a reserved keyword</b> -- <c>"Class"</c>, <c>"Event"</c> and
    /// <c>"Params"</c> all lower-case into one. That is by design: this method answers "how is this
    /// name spelled in camelCase", which is a different question from "is this safe to emit at a
    /// declaration site", and a caller splicing the result into a longer identifier
    /// (<c>classFactory</c>) must not get a stray <c>@</c> in the middle of it. Wrap the result in
    /// <see cref="EscapeKeyword"/> at the point of use -- <c>EscapeKeyword(ToCamelCaseIdentifier(name))</c>
    /// -- whenever the fragment is emitted as a parameter or local name on its own.
    /// <see cref="ToPascalCaseIdentifier"/> needs no such care, because every C# reserved keyword is
    /// lower-case.
    /// </remarks>
    public static string ToCamelCaseIdentifier(string? text, string fallback = "identifier")
    {
        var pascal = BuildPascalCore(text);
        return pascal is null ? fallback : LowerLeadingRun(pascal);
    }

    /// <summary>
    /// Joins already-valid identifier fragments into a single identifier, e.g. the containing-type
    /// chain <c>["Outer", "Inner"]</c> into <c>"Outer_Inner"</c>, which is how a generator flattens
    /// a nested type's name into a top-level one.
    /// </summary>
    /// <param name="segments">
    /// The fragments, in the order they should appear. Each one is assumed to already be a valid
    /// C# identifier: this method joins, it never sanitizes. Use
    /// <see cref="ToPascalCaseIdentifier"/> first if that assumption does not hold.
    /// </param>
    /// <param name="separator">The character written between two consecutive fragments.</param>
    /// <returns>
    /// The joined identifier. <see langword="null"/> and empty fragments are skipped rather than
    /// joined, so the result never starts or ends with <paramref name="separator"/> and never
    /// contains two of them in a row. An empty list (or one holding nothing but empty fragments)
    /// yields <see cref="string.Empty"/>.
    /// </returns>
    public static string JoinIdentifierSegments(IReadOnlyList<string> segments, char separator = '_')
    {
        Debug.Assert(segments is not null, "segments must not be null.");

        var builder = new StringBuilder();

        for (var i = 0; i < segments!.Count; i++)
        {
            var segment = segments[i];
            if (string.IsNullOrEmpty(segment))
            {
                continue;
            }

            if (builder.Length > 0)
            {
                builder.Append(separator);
            }

            builder.Append(segment);
        }

        return builder.ToString();
    }

    /// <summary>
    /// Prefixes <paramref name="identifier"/> with <c>@</c> if it is a reserved C# keyword (e.g.
    /// <c>"class"</c> becomes <c>"@class"</c>); otherwise returns it unchanged. Contextual
    /// keywords (such as <c>var</c> or <c>nameof</c>) are never escaped because they remain valid
    /// identifiers in every position.
    /// </summary>
    /// <param name="identifier">The candidate identifier.</param>
    /// <returns>An identifier that is always safe to emit at a member or local declaration site.</returns>
    public static string EscapeKeyword(string identifier)
    {
        Debug.Assert(identifier is not null, "identifier must not be null.");

        return ReservedKeywords.Contains(identifier) ? "@" + identifier : identifier;
    }

    private static string? BuildPascalCore(string? text)
    {
        if (string.IsNullOrEmpty(text))
        {
            return null;
        }

        var builder = new StringBuilder(text!.Length);
        var startOfSegment = true;

        foreach (var c in text)
        {
            if (!char.IsLetterOrDigit(c))
            {
                startOfSegment = true;
                continue;
            }

            builder.Append(startOfSegment ? char.ToUpperInvariant(c) : c);
            startOfSegment = false;
        }

        if (builder.Length == 0)
        {
            return null;
        }

        // A valid C# identifier cannot start with a digit.
        if (char.IsDigit(builder[0]))
        {
            builder.Insert(0, '_');
        }

        return builder.ToString();
    }

    private static string LowerLeadingRun(string value)
    {
        // BuildPascalCore never returns an empty string (it returns null instead), so callers of
        // this method always pass at least one character.
        Debug.Assert(value.Length > 0, "value must not be empty.");

        if (!char.IsUpper(value[0]))
        {
            return value;
        }

        var chars = value.ToCharArray();

        for (var i = 0; i < chars.Length; i++)
        {
            // Only the leading upper-case letter is part of the run when the second character is
            // already lower case, e.g. "Service" -> lower only chars[0].
            if (i == 1 && !char.IsUpper(chars[i]))
            {
                break;
            }

            // Stop before lowering the last letter of an all-caps run when it starts a new word,
            // e.g. "IOService" -> lower "IO" but keep the "S" that begins "Service".
            var hasNext = i + 1 < chars.Length;
            if (hasNext && i > 0 && !char.IsUpper(chars[i + 1]))
            {
                break;
            }

            chars[i] = char.ToLowerInvariant(chars[i]);
        }

        return new string(chars);
    }
}
