// <auto-generated/>
#pragma warning disable
#nullable enable

using System.Globalization;
using Microsoft.CodeAnalysis;

namespace SsalKit.Generators.Toolkit;

/// <summary>
/// Builds <see cref="DiagnosticDescriptor"/> instances that share a common id prefix and
/// category, reducing the boilerplate of a generator's diagnostic descriptor table.
/// </summary>
/// <remarks>
/// Every descriptor produced by a given factory instance is enabled by default and has an id of
/// the form <c>{idPrefix}{id:D3}</c>, e.g. <c>"SSAL001"</c> for prefix <c>"SSAL"</c> and id
/// <c>1</c>.
/// </remarks>
internal sealed class DiagnosticDescriptorFactory
{
    private readonly string _idPrefix;
    private readonly string _category;

    /// <summary>
    /// Initializes a new instance of the <see cref="DiagnosticDescriptorFactory"/> class.
    /// </summary>
    /// <param name="idPrefix">The prefix shared by every descriptor's id, e.g. <c>"SSAL"</c>.</param>
    /// <param name="category">The category shared by every descriptor, e.g. <c>"SsalKit.Guard"</c>.</param>
    public DiagnosticDescriptorFactory(string idPrefix, string category)
    {
        _idPrefix = idPrefix;
        _category = category;
    }

    /// <summary>
    /// Creates a descriptor with <see cref="DiagnosticSeverity.Error"/> severity.
    /// </summary>
    /// <param name="id">The numeric id, formatted with three digits and appended to the prefix.</param>
    /// <param name="title">The short, human-readable title of the diagnostic.</param>
    /// <param name="messageFormat">The composite format string used for the diagnostic message.</param>
    /// <param name="description">The longer description of the diagnostic.</param>
    /// <param name="customTags">Additional custom tags to attach to the descriptor, if any.</param>
    /// <returns>A new <see cref="DiagnosticDescriptor"/> with <see cref="DiagnosticSeverity.Error"/> severity.</returns>
    public DiagnosticDescriptor Error(
        int id,
        string title,
        string messageFormat,
        string description,
        params string[] customTags) =>
        Create(id, title, messageFormat, description, DiagnosticSeverity.Error, customTags);

    /// <summary>
    /// Creates a descriptor with <see cref="DiagnosticSeverity.Warning"/> severity.
    /// </summary>
    /// <param name="id">The numeric id, formatted with three digits and appended to the prefix.</param>
    /// <param name="title">The short, human-readable title of the diagnostic.</param>
    /// <param name="messageFormat">The composite format string used for the diagnostic message.</param>
    /// <param name="description">The longer description of the diagnostic.</param>
    /// <param name="customTags">Additional custom tags to attach to the descriptor, if any.</param>
    /// <returns>A new <see cref="DiagnosticDescriptor"/> with <see cref="DiagnosticSeverity.Warning"/> severity.</returns>
    public DiagnosticDescriptor Warning(
        int id,
        string title,
        string messageFormat,
        string description,
        params string[] customTags) =>
        Create(id, title, messageFormat, description, DiagnosticSeverity.Warning, customTags);

    private DiagnosticDescriptor Create(
        int id,
        string title,
        string messageFormat,
        string description,
        DiagnosticSeverity severity,
        string[] customTags)
    {
        var fullId = _idPrefix + id.ToString("D3", CultureInfo.InvariantCulture);

        return new DiagnosticDescriptor(
            fullId,
            title,
            messageFormat,
            _category,
            severity,
            isEnabledByDefault: true,
            description: description,
            customTags: customTags);
    }
}
