// <auto-generated/>
#pragma warning disable
#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SsalKit.Generators.Toolkit;

/// <summary>
/// An equatable, compilation-independent stand-in for a <see cref="Diagnostic"/>, so a diagnostic
/// can travel through the incremental pipeline without pinning a <see cref="SyntaxTree"/> (and,
/// through it, an entire <see cref="Compilation"/>) in the generator's cache.
/// </summary>
/// <remarks>
/// <para>
/// Equality is by value across all three components, which is the whole point of the type: a
/// pipeline stage that produces the same diagnostics twice must compare equal, or the generator
/// re-reports on every keystroke. <see cref="DiagnosticDescriptor"/> instances are shared static
/// singletons that already compare by value, so holding one here is safe.
/// </para>
/// <para>
/// That is also why the message arguments are typed as <see cref="EquatableArray{T}"/> of
/// <see cref="string"/> rather than the <c>object?[]</c> that
/// <see cref="Diagnostic.Create(DiagnosticDescriptor, Location?, object?[])"/> itself takes. An
/// arbitrary <see cref="object"/> argument carries whatever equality its own type happens to
/// implement — reference equality, for most — so two runs that produced the "same" diagnostic
/// could compare unequal and defeat the cache, or, worse, an argument could be a Roslyn symbol or
/// syntax node and root a whole <see cref="Compilation"/> in it. Fixing the element type to
/// <see cref="string"/> makes both impossible by construction.
/// </para>
/// <para>
/// Formatting therefore happens at the call site, before the value enters the pipeline: whatever
/// a caller wants spliced into the message format has to be rendered to a string first, and
/// <see cref="ToDiagnostic"/> passes those strings through to
/// <see cref="Diagnostic.Create(DiagnosticDescriptor, Location?, object?[])"/> verbatim. Any
/// culture-sensitive conversion (numbers, dates) should be done with an invariant format so the
/// diagnostic text does not vary with the build machine's locale.
/// </para>
/// </remarks>
internal sealed class DiagnosticInfo : IEquatable<DiagnosticInfo>
{
    /// <summary>
    /// Creates a diagnostic description from a pre-built argument array.
    /// </summary>
    /// <param name="descriptor">The rule that fired.</param>
    /// <param name="location">
    /// Where to report, or <see langword="null"/> to report with no location.
    /// </param>
    /// <param name="messageArgs">The arguments spliced into the descriptor's message format.</param>
    public DiagnosticInfo(
        DiagnosticDescriptor descriptor, LocationInfo? location, EquatableArray<string> messageArgs)
    {
        Descriptor = descriptor;
        Location = location;
        MessageArgs = messageArgs;
    }

    /// <summary>
    /// Creates a diagnostic description from a variable number of message arguments.
    /// </summary>
    /// <param name="descriptor">The rule that fired.</param>
    /// <param name="location">
    /// Where to report, or <see langword="null"/> to report with no location.
    /// </param>
    /// <param name="messageArgs">The arguments spliced into the descriptor's message format.</param>
    public DiagnosticInfo(DiagnosticDescriptor descriptor, LocationInfo? location, params string[] messageArgs)
        : this(descriptor, location, new EquatableArray<string>(ImmutableArray.Create(messageArgs)))
    {
    }

    /// <summary>
    /// The rule that fired.
    /// </summary>
    public DiagnosticDescriptor Descriptor { get; }

    /// <summary>
    /// Where to report, or <see langword="null"/> to report with no location.
    /// </summary>
    public LocationInfo? Location { get; }

    /// <summary>
    /// The arguments spliced into the descriptor's message format, already rendered to strings.
    /// See the type's remarks for why the element type is fixed to <see cref="string"/>.
    /// </summary>
    public EquatableArray<string> MessageArgs { get; }

    /// <summary>
    /// Rehydrates a reportable <see cref="Diagnostic"/>. Called only at the source-output stage,
    /// never while a value is sitting in the pipeline cache.
    /// </summary>
    /// <returns>A diagnostic ready to hand to <c>ReportDiagnostic</c>.</returns>
    public Diagnostic ToDiagnostic()
    {
        var args = new object?[MessageArgs.Length];
        for (var i = 0; i < MessageArgs.Length; i++)
        {
            args[i] = MessageArgs[i];
        }

        return Diagnostic.Create(Descriptor, Location?.ToLocation(), args);
    }

    /// <inheritdoc />
    public bool Equals(DiagnosticInfo? other)
    {
        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return other is not null
            && EqualityComparer<DiagnosticDescriptor>.Default.Equals(Descriptor, other.Descriptor)
            && EqualityComparer<LocationInfo?>.Default.Equals(Location, other.Location)
            && MessageArgs.Equals(other.MessageArgs);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as DiagnosticInfo);

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = 17;
        hash = (hash * 31) + Descriptor.GetHashCode();
        hash = (hash * 31) + (Location?.GetHashCode() ?? 0);
        hash = (hash * 31) + MessageArgs.GetHashCode();
        return hash;
    }

    /// <summary>
    /// Compares two descriptions by value.
    /// </summary>
    /// <param name="left">The left operand, which may be <see langword="null"/>.</param>
    /// <param name="right">The right operand, which may be <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when both are <see langword="null"/> or equal by value.</returns>
    public static bool operator ==(DiagnosticInfo? left, DiagnosticInfo? right) =>
        left is null ? right is null : left.Equals(right);

    /// <summary>
    /// Compares two descriptions by value.
    /// </summary>
    /// <param name="left">The left operand, which may be <see langword="null"/>.</param>
    /// <param name="right">The right operand, which may be <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the two differ.</returns>
    public static bool operator !=(DiagnosticInfo? left, DiagnosticInfo? right) => !(left == right);
}

/// <summary>
/// The value-equatable projection of a <see cref="Location"/> in source: everything
/// <see cref="Location.Create(string, TextSpan, LinePositionSpan)"/> needs, and nothing that
/// references a syntax tree.
/// </summary>
internal sealed class LocationInfo : IEquatable<LocationInfo>
{
    /// <summary>
    /// Creates a projection from its three components.
    /// </summary>
    /// <param name="filePath">The path of the source file the location belongs to.</param>
    /// <param name="textSpan">The character span within that file.</param>
    /// <param name="lineSpan">The line/column span within that file.</param>
    public LocationInfo(string filePath, TextSpan textSpan, LinePositionSpan lineSpan)
    {
        FilePath = filePath;
        TextSpan = textSpan;
        LineSpan = lineSpan;
    }

    /// <summary>
    /// The path of the source file the location belongs to.
    /// </summary>
    public string FilePath { get; }

    /// <summary>
    /// The character span within the source file.
    /// </summary>
    public TextSpan TextSpan { get; }

    /// <summary>
    /// The line/column span within the source file.
    /// </summary>
    public LinePositionSpan LineSpan { get; }

    /// <summary>
    /// Rebuilds an external <see cref="Location"/> from the projection.
    /// </summary>
    /// <returns>A location equivalent, for reporting purposes, to the projected one.</returns>
    public Location ToLocation() => Location.Create(FilePath, TextSpan, LineSpan);

    /// <summary>
    /// Projects <paramref name="location"/>, or returns <see langword="null"/> when it is not a
    /// location in source (e.g. a metadata or "none" location), which
    /// <see cref="Diagnostic.Create(DiagnosticDescriptor, Location?, object?[])"/> accepts as-is.
    /// </summary>
    /// <param name="location">The location to project, which may be <see langword="null"/>.</param>
    /// <returns>The projection, or <see langword="null"/>.</returns>
    public static LocationInfo? CreateFrom(Location? location) =>
        location?.SourceTree is null
            ? null
            : new LocationInfo(location.SourceTree.FilePath, location.SourceSpan, location.GetLineSpan().Span);

    /// <summary>
    /// Projects the location of <paramref name="node"/>.
    /// </summary>
    /// <param name="node">The node to project, which may be <see langword="null"/>.</param>
    /// <returns>The projection, or <see langword="null"/>.</returns>
    public static LocationInfo? CreateFrom(SyntaxNode? node) => node is null ? null : CreateFrom(node.GetLocation());

    /// <inheritdoc />
    public bool Equals(LocationInfo? other)
    {
        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return other is not null
            && string.Equals(FilePath, other.FilePath, StringComparison.Ordinal)
            && TextSpan.Equals(other.TextSpan)
            && LineSpan.Equals(other.LineSpan);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj) => Equals(obj as LocationInfo);

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = 17;
        hash = (hash * 31) + FilePath.GetHashCode();
        hash = (hash * 31) + TextSpan.GetHashCode();
        hash = (hash * 31) + LineSpan.GetHashCode();
        return hash;
    }

    /// <summary>
    /// Compares two projections by value.
    /// </summary>
    /// <param name="left">The left operand, which may be <see langword="null"/>.</param>
    /// <param name="right">The right operand, which may be <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when both are <see langword="null"/> or equal by value.</returns>
    public static bool operator ==(LocationInfo? left, LocationInfo? right) =>
        left is null ? right is null : left.Equals(right);

    /// <summary>
    /// Compares two projections by value.
    /// </summary>
    /// <param name="left">The left operand, which may be <see langword="null"/>.</param>
    /// <param name="right">The right operand, which may be <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the two differ.</returns>
    public static bool operator !=(LocationInfo? left, LocationInfo? right) => !(left == right);
}
