// <auto-generated/>
#pragma warning disable
#nullable enable

using System;
using System.Text;

namespace SsalKit.Generators.Toolkit;

/// <summary>
/// Turns an arbitrary candidate string (typically a type's fully qualified name) into a value
/// safe to pass as the <c>hintName</c> argument of
/// <c>Microsoft.CodeAnalysis.GeneratorExecutionContext.AddSource</c> /
/// <c>SourceProductionContext.AddSource</c>.
/// </summary>
/// <remarks>
/// Roslyn accepts a fairly permissive character set in hint names (letters, digits, <c>_</c>,
/// <c>.</c>, <c>,</c>, <c>-</c>, <c>+</c>, <c>` </c>, parentheses, brackets, and spaces), but two
/// characters from that allowed set are still replaced for readability: the backtick used in
/// generic arity markers (e.g. <c>Foo`1</c>) and the plus sign used for nested types
/// (e.g. <c>Outer+Inner</c>). Every character outside the allowed set (such as <c>&lt;</c>,
/// <c>&gt;</c>, <c>:</c>, <c>/</c>, or <c>\</c>) is replaced as well.
/// </remarks>
internal static class HintNameSanitizer
{
    private const int MaxLength = 200;

    /// <summary>
    /// Sanitizes <paramref name="candidate"/> into a safe hint name, ensuring it ends with
    /// <paramref name="suffix"/> and does not exceed the practical length Roslyn/file systems
    /// tolerate for a single generated file name.
    /// </summary>
    /// <param name="candidate">
    /// The raw candidate, typically a type's fully qualified or metadata name. A
    /// <see langword="null"/>, empty, or whitespace-only value is replaced with
    /// <c>"Generated"</c>.
    /// </param>
    /// <param name="suffix">
    /// The suffix the result must end with. If <paramref name="candidate"/> already ends with
    /// this suffix, it is not appended a second time.
    /// </param>
    /// <returns>
    /// A hint name composed only of characters Roslyn's <c>AddSource</c> accepts, at most 200
    /// characters long (suffix included). When truncation is required, characters are removed
    /// from the front so the more distinguishing tail of the name (and the suffix) survive.
    /// </returns>
    public static string Sanitize(string candidate, string suffix = ".g.cs")
    {
        var basis = string.IsNullOrWhiteSpace(candidate) ? "Generated" : candidate;

        var builder = new StringBuilder(basis.Length);
        foreach (var c in basis)
        {
            builder.Append(IsPassthroughChar(c) ? c : '_');
        }

        var sanitized = builder.ToString();

        var result = sanitized.EndsWith(suffix, StringComparison.Ordinal)
            ? sanitized
            : sanitized + suffix;

        if (result.Length > MaxLength)
        {
            result = result.Substring(result.Length - MaxLength);
        }

        return result;
    }

    private static bool IsPassthroughChar(char c) =>
        char.IsLetterOrDigit(c)
        || c == '_'
        || c == '.'
        || c == ','
        || c == '-'
        || c == '('
        || c == ')'
        || c == '['
        || c == ']'
        || c == ' ';
}
