// <auto-generated/>
#pragma warning disable
#nullable enable

using System;
using System.Text;

namespace SsalKit.Generators.Toolkit;

/// <summary>
/// Writes C# source text with automatic, stack-based indentation tracking, suitable for building
/// up the body of a generated source file.
/// </summary>
/// <remarks>
/// Line breaks are always emitted as <c>"\n"</c> regardless of the host operating system, to keep
/// generated output byte-for-byte deterministic across build machines. Blank lines never carry
/// trailing indentation whitespace, which keeps diffs of generated files stable across edits that
/// change the surrounding indentation depth.
/// </remarks>
internal sealed class IndentedCodeWriter
{
    private const string NewLine = "\n";

    private readonly StringBuilder _builder;
    private readonly string _indentUnit;
    private int _indentLevel;
    private bool _atLineStart;

    /// <summary>
    /// Initializes a new instance of the <see cref="IndentedCodeWriter"/> class.
    /// </summary>
    /// <param name="indentSize">The number of spaces that make up a single indentation level.</param>
    public IndentedCodeWriter(int indentSize = 4)
    {
        _builder = new StringBuilder();
        _indentUnit = new string(' ', indentSize);
        _indentLevel = 0;
        _atLineStart = true;
    }

    /// <summary>
    /// Writes the standard generated-file header: <c>// &lt;auto-generated/&gt;</c>, followed by
    /// <c>#nullable enable</c>, followed by a blank line.
    /// </summary>
    public void WriteAutoGeneratedHeader()
    {
        WriteLine("// <auto-generated/>");
        WriteLine("#nullable enable");
        WriteLine();
    }

    /// <summary>
    /// Appends <paramref name="text"/> to the current line without a trailing line break.
    /// Indentation is written first if nothing has been written since the last line break.
    /// </summary>
    /// <param name="text">The text to append.</param>
    public void Write(string text)
    {
        if (text.Length == 0)
        {
            return;
        }

        WriteIndentIfAtLineStart();
        _builder.Append(text);
    }

    /// <summary>
    /// Writes <paramref name="line"/> followed by a line break, applying indentation first.
    /// </summary>
    /// <param name="line">The line content to write, excluding the line break.</param>
    public void WriteLine(string line)
    {
        if (line.Length > 0)
        {
            WriteIndentIfAtLineStart();
            _builder.Append(line);
        }

        _builder.Append(NewLine);
        _atLineStart = true;
    }

    /// <summary>
    /// Writes a blank line. No indentation whitespace is emitted for the blank line.
    /// </summary>
    public void WriteLine()
    {
        _builder.Append(NewLine);
        _atLineStart = true;
    }

    /// <summary>
    /// Increases the indentation level until the returned scope is disposed.
    /// </summary>
    /// <returns>A scope that restores the previous indentation level when disposed.</returns>
    public IndentationScope Indent()
    {
        _indentLevel++;
        return new IndentationScope(this);
    }

    /// <summary>
    /// Writes <paramref name="header"/>, an opening brace on its own line, and increases the
    /// indentation level. A closing <c>}</c> is written when the returned scope is disposed.
    /// </summary>
    /// <param name="header">The text to write before the opening brace (e.g. a method signature).</param>
    /// <returns>A scope that writes the closing brace and restores indentation when disposed.</returns>
    public BlockScope Block(string header) => Block(header, "}");

    /// <summary>
    /// Writes <paramref name="header"/>, an opening brace on its own line, and increases the
    /// indentation level. <paramref name="closer"/> is written when the returned scope is
    /// disposed, which allows callers to supply a trailing token such as <c>"};"</c>.
    /// </summary>
    /// <param name="header">The text to write before the opening brace (e.g. a method signature).</param>
    /// <param name="closer">The text to write in place of the closing brace when the scope ends.</param>
    /// <returns>A scope that writes <paramref name="closer"/> and restores indentation when disposed.</returns>
    public BlockScope Block(string header, string closer)
    {
        WriteLine(header);
        WriteLine("{");
        _indentLevel++;
        return new BlockScope(this, closer);
    }

    /// <summary>
    /// Returns the source text accumulated so far.
    /// </summary>
    public override string ToString() => _builder.ToString();

    private void WriteIndentIfAtLineStart()
    {
        if (!_atLineStart)
        {
            return;
        }

        for (var i = 0; i < _indentLevel; i++)
        {
            _builder.Append(_indentUnit);
        }

        _atLineStart = false;
    }

    private void EndIndent()
    {
        _indentLevel--;
    }

    private void EndBlock(string closer)
    {
        _indentLevel--;
        WriteLine(closer);
    }

    /// <summary>
    /// A disposable scope returned by <see cref="IndentedCodeWriter.Indent"/> that restores the
    /// writer's indentation level when disposed.
    /// </summary>
    internal readonly struct IndentationScope : IDisposable
    {
        private readonly IndentedCodeWriter _writer;

        internal IndentationScope(IndentedCodeWriter writer)
        {
            _writer = writer;
        }

        /// <summary>
        /// Decreases the writer's indentation level by one.
        /// </summary>
        public void Dispose() => _writer.EndIndent();
    }

    /// <summary>
    /// A disposable scope returned by <see cref="IndentedCodeWriter.Block(string)"/> that writes
    /// a closing token and restores the writer's indentation level when disposed.
    /// </summary>
    internal readonly struct BlockScope : IDisposable
    {
        private readonly IndentedCodeWriter _writer;
        private readonly string _closer;

        internal BlockScope(IndentedCodeWriter writer, string closer)
        {
            _writer = writer;
            _closer = closer;
        }

        /// <summary>
        /// Decreases the writer's indentation level and writes the closing token.
        /// </summary>
        public void Dispose() => _writer.EndBlock(_closer);
    }
}
