// <auto-generated/>
#pragma warning disable
#nullable enable

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;

namespace SsalKit.Generators.Toolkit;

/// <summary>
/// Writes C# source text with automatic, stack-based indentation tracking, suitable for building
/// up the body of a generated source file.
/// </summary>
/// <remarks>
/// Line breaks are always emitted as <c>"\n"</c> regardless of the host operating system, to keep
/// generated output byte-for-byte deterministic across build machines. Blank lines never carry
/// trailing indentation whitespace, which keeps diffs of generated files stable across edits that
/// change the surrounding indentation depth.
/// </remarks>
/// <remarks>
/// <b>Indentation is applied per write, not per line.</b> The writer indents when something is
/// written at the start of a line and then treats the text as opaque, so a string that itself
/// contains line breaks (a raw string literal holding a whole method body, say) has only its
/// <i>first</i> line indented; the rest land at whatever column the embedded text already carries.
/// Write such blocks one line at a time -- <c>foreach (var line in block.Split('\n'))
/// writer.WriteLine(line.TrimEnd('\r'))</c> -- or accept the embedded layout as authoritative and
/// write it at indentation level zero.
/// </remarks>
internal sealed class IndentedCodeWriter
{
    private const string NewLine = "\n";

    private readonly StringBuilder _builder;
    private readonly string _indentUnit;
    private int _indentLevel;
    private bool _atLineStart;

    /// <summary>
    /// Initializes a new instance of the <see cref="IndentedCodeWriter"/> class.
    /// </summary>
    /// <param name="indentSize">The number of spaces that make up a single indentation level.</param>
    public IndentedCodeWriter(int indentSize = 4)
    {
        _builder = new StringBuilder();
        _indentUnit = new string(' ', indentSize);
        _indentLevel = 0;
        _atLineStart = true;
    }

    /// <summary>
    /// Writes the standard generated-file header: <c>// &lt;auto-generated/&gt;</c>, optionally
    /// followed by <c>#pragma warning disable</c>, followed by <c>#nullable enable</c>, followed by
    /// a blank line.
    /// </summary>
    /// <param name="suppressWarnings">
    /// <see langword="true"/> to insert a bare <c>#pragma warning disable</c> line between the
    /// <c>// &lt;auto-generated/&gt;</c> marker and <c>#nullable enable</c>, which clears every
    /// warning for the rest of the file. Generated code is compiled with the consumer's warning
    /// configuration, so a project with <c>TreatWarningsAsErrors</c> and a strict analyzer set can
    /// otherwise fail to build over a file its author cannot edit.
    /// </param>
    /// <remarks>
    /// The parameter defaults to <see langword="false"/>, so the header an existing generator emits
    /// is unchanged: the pragma is opt-in, because suppressing everything also hides a real warning
    /// (an obsolete API the generator emits a call to, say) that the generator's author would want
    /// to see.
    /// </remarks>
    public void WriteAutoGeneratedHeader(bool suppressWarnings = false)
    {
        WriteLine("// <auto-generated/>");

        if (suppressWarnings)
        {
            WriteLine("#pragma warning disable");
        }

        WriteLine("#nullable enable");
        WriteLine();
    }

    /// <summary>
    /// Appends <paramref name="text"/> to the current line without a trailing line break.
    /// Indentation is written first if nothing has been written since the last line break.
    /// </summary>
    /// <param name="text">
    /// The text to append. It is written verbatim: any line break inside it leaves the following
    /// lines un-indented, and the writer still considers itself mid-line afterwards. See the type's
    /// remarks.
    /// </param>
    public void Write(string text)
    {
        if (text.Length == 0)
        {
            return;
        }

        WriteIndentIfAtLineStart();
        _builder.Append(text);
    }

    /// <summary>
    /// Writes <paramref name="line"/> followed by a line break, applying indentation first.
    /// </summary>
    /// <param name="line">
    /// The line content to write, excluding the line break. Only the first line of a value that
    /// already contains line breaks is indented; see the type's remarks.
    /// </param>
    public void WriteLine(string line)
    {
        if (line.Length > 0)
        {
            WriteIndentIfAtLineStart();
            _builder.Append(line);
        }

        _builder.Append(NewLine);
        _atLineStart = true;
    }

    /// <summary>
    /// Writes a blank line. No indentation whitespace is emitted for the blank line.
    /// </summary>
    public void WriteLine()
    {
        _builder.Append(NewLine);
        _atLineStart = true;
    }

    /// <summary>
    /// Writes one XML documentation comment line: <paramref name="content"/> prefixed with
    /// <c>"/// "</c>, at the current indentation level.
    /// </summary>
    /// <param name="content">
    /// The comment content, without the leading slashes. An empty string writes a bare <c>///</c>
    /// with no trailing space, so generated documentation blocks carry no trailing whitespace.
    /// </param>
    public void WriteDocLine(string content)
    {
        WriteLine(content.Length == 0 ? "///" : "/// " + content);
    }

    /// <summary>
    /// Writes a run of XML documentation comment lines, one per element, each through
    /// <see cref="WriteDocLine"/>.
    /// </summary>
    /// <param name="contents">The comment contents, without the leading slashes.</param>
    public void WriteDocLines(params string[] contents)
    {
        foreach (var content in contents)
        {
            WriteDocLine(content);
        }
    }

    /// <summary>
    /// Writes a run of XML documentation comment lines from an arbitrary sequence, one per element,
    /// each through <see cref="WriteDocLine"/>.
    /// </summary>
    /// <param name="contents">
    /// The comment contents, without the leading slashes. The sequence is enumerated exactly once,
    /// as it is written, so a lazily built one (a filtered or conditionally extended run of doc
    /// lines, say) never has to be materialized into an array first. An empty sequence writes
    /// nothing.
    /// </param>
    /// <remarks>
    /// This overload never displaces <see cref="WriteDocLines(string[])"/> for callers that pass
    /// loose arguments or an actual <see cref="string"/> array: <c>string[]</c> is the more specific
    /// parameter type, so existing call sites bind exactly as they did before.
    /// </remarks>
    public void WriteDocLines(IEnumerable<string> contents)
    {
        foreach (var content in contents)
        {
            WriteDocLine(content);
        }
    }

    /// <summary>
    /// Increases the indentation level until the returned scope is disposed.
    /// </summary>
    /// <returns>A scope that restores the previous indentation level when disposed.</returns>
    public IndentationScope Indent()
    {
        _indentLevel++;
        return new IndentationScope(this);
    }

    /// <summary>
    /// Writes <paramref name="header"/>, an opening brace on its own line, and increases the
    /// indentation level. A closing <c>}</c> is written when the returned scope is disposed.
    /// </summary>
    /// <param name="header">The text to write before the opening brace (e.g. a method signature).</param>
    /// <returns>A scope that writes the closing brace and restores indentation when disposed.</returns>
    public BlockScope Block(string header) => Block(header, "}");

    /// <summary>
    /// Writes <paramref name="header"/>, an opening brace on its own line, and increases the
    /// indentation level. <paramref name="closer"/> is written when the returned scope is
    /// disposed, which allows callers to supply a trailing token such as <c>"};"</c>.
    /// </summary>
    /// <param name="header">The text to write before the opening brace (e.g. a method signature).</param>
    /// <param name="closer">The text to write in place of the closing brace when the scope ends.</param>
    /// <returns>A scope that writes <paramref name="closer"/> and restores indentation when disposed.</returns>
    public BlockScope Block(string header, string closer)
    {
        WriteLine(header);
        WriteLine("{");
        _indentLevel++;
        return new BlockScope(this, closer);
    }

    /// <summary>
    /// Returns the source text accumulated so far.
    /// </summary>
    public override string ToString() => _builder.ToString();

    private void WriteIndentIfAtLineStart()
    {
        if (!_atLineStart)
        {
            return;
        }

        for (var i = 0; i < _indentLevel; i++)
        {
            _builder.Append(_indentUnit);
        }

        _atLineStart = false;
    }

    private void EndIndent()
    {
        // A scope is only ever created by Indent(), which raised the level first, so reaching zero
        // here means a scope was disposed twice or disposed out of order -- a caller bug that would
        // otherwise silently emit negatively indented (i.e. flattened) code from then on.
        Debug.Assert(_indentLevel > 0, "An indentation scope was disposed more than once, or out of order.");

        _indentLevel--;
    }

    private void EndBlock(string closer)
    {
        Debug.Assert(_indentLevel > 0, "A block scope was disposed more than once, or out of order.");

        _indentLevel--;
        WriteLine(closer);
    }

    /// <summary>
    /// A disposable scope returned by <see cref="IndentedCodeWriter.Indent"/> that restores the
    /// writer's indentation level when disposed.
    /// </summary>
    internal readonly struct IndentationScope : IDisposable
    {
        private readonly IndentedCodeWriter _writer;

        internal IndentationScope(IndentedCodeWriter writer)
        {
            _writer = writer;
        }

        /// <summary>
        /// Decreases the writer's indentation level by one.
        /// </summary>
        public void Dispose() => _writer.EndIndent();
    }

    /// <summary>
    /// A disposable scope returned by <see cref="IndentedCodeWriter.Block(string)"/> that writes
    /// a closing token and restores the writer's indentation level when disposed.
    /// </summary>
    internal readonly struct BlockScope : IDisposable
    {
        private readonly IndentedCodeWriter _writer;
        private readonly string _closer;

        internal BlockScope(IndentedCodeWriter writer, string closer)
        {
            _writer = writer;
            _closer = closer;
        }

        /// <summary>
        /// Decreases the writer's indentation level and writes the closing token.
        /// </summary>
        public void Dispose() => _writer.EndBlock(_closer);
    }
}
