// <auto-generated/>
#pragma warning disable
#nullable enable

// Compiler polyfill required to use C# 9+ <c>init</c> accessors and <c>record</c> declarations
// while targeting netstandard2.0, whose reference assemblies do not ship this type. The compiler
// only needs the type to *exist* with this exact name and namespace; the body is never used.
//
// This is the one embedded source that does not live in the SsalKit.Generators.Toolkit namespace,
// because the compiler looks the type up by its fixed fully qualified name.
//
// Define SSALKIT_GENERATORS_TOOLKIT_EXCLUDE_ISEXTERNALINIT in your project to opt out when your
// compilation already declares this type (from your own polyfill or another package), which would
// otherwise be a CS0101 duplicate definition:
//
//   <PropertyGroup>
//     <DefineConstants>$(DefineConstants);SSALKIT_GENERATORS_TOOLKIT_EXCLUDE_ISEXTERNALINIT</DefineConstants>
//   </PropertyGroup>
//
// No other file in this package depends on this one: the toolkit's own sources deliberately avoid
// the syntax it enables, so excluding it never breaks them.
#if !SSALKIT_GENERATORS_TOOLKIT_EXCLUDE_ISEXTERNALINIT

namespace System.Runtime.CompilerServices;

/// <summary>
/// Marker type the C# compiler requires to emit <c>init</c> accessors (and therefore
/// <c>record</c> declarations) on target frameworks that do not provide it.
/// </summary>
internal static class IsExternalInit
{
}

#endif
