// <auto-generated/>
#pragma warning disable
#nullable enable

using System;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace SsalKit.Generators.Toolkit;

/// <summary>
/// The symbol-level questions almost every generator ends up asking: how a type is written in
/// generated code, whether the generated code may name it at all, whether it is generic, and how a
/// run's diagnostics are ordered so the sequence is a function of the compilation alone.
/// </summary>
/// <remarks>
/// Nothing here reads syntax or needs a <see cref="Compilation"/>: these are single-symbol facts,
/// which is what makes them safe to call from a pipeline transform. Anything that has to consult
/// the compilation -- cross-assembly <c>[InternalsVisibleTo]</c> grants, <c>extern alias</c>
/// reachability -- is deliberately out of scope, because the answer then depends on which
/// compilation is asking.
/// </remarks>
internal static class SymbolFacts
{
    /// <summary>
    /// The <c>global::</c>-prefixed fully qualified name, which is how a type reference in
    /// generated code should be written: it binds the same way no matter what <c>using</c>
    /// directives or same-named types happen to be in scope at the generated file's position.
    /// </summary>
    /// <param name="symbol">The symbol to name.</param>
    /// <returns>The fully qualified name, e.g. <c>global::System.Collections.Generic.List&lt;int&gt;</c>.</returns>
    public static string ToFqn(ISymbol symbol) =>
        symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    /// <summary>
    /// The dotted name of the namespace containing <paramref name="symbol"/>, or
    /// <see cref="string.Empty"/> when it sits in the global namespace.
    /// </summary>
    /// <remarks>
    /// The empty string is the useful answer rather than <c>"&lt;global namespace&gt;"</c> (what
    /// <see cref="ISymbol.ToDisplayString(SymbolDisplayFormat)"/> would give) because it is what a
    /// generator needs to decide whether to emit a namespace declaration at all, and because it
    /// concatenates correctly wherever the name is spliced into an identifier or a hint name.
    /// </remarks>
    /// <param name="symbol">The symbol whose containing namespace is wanted.</param>
    /// <returns>The namespace name, or <see cref="string.Empty"/> for the global namespace.</returns>
    public static string GetContainingNamespaceName(ISymbol symbol)
    {
        var containingNamespace = symbol.ContainingNamespace;

        return containingNamespace is null || containingNamespace.IsGlobalNamespace
            ? string.Empty
            : containingNamespace.ToDisplayString();
    }

    /// <summary>
    /// Returns <see langword="true"/> when <paramref name="type"/> and every type containing it are
    /// <see langword="public"/>, which is the only case where a generated member may expose the
    /// type and still be declared <see langword="public"/> itself without an
    /// inconsistent-accessibility error.
    /// </summary>
    /// <param name="type">The type to inspect.</param>
    /// <returns><see langword="true"/> when the whole nesting chain is public.</returns>
    public static bool IsEffectivelyPublic(INamedTypeSymbol type)
    {
        for (INamedTypeSymbol? current = type; current is not null; current = current.ContainingType)
        {
            if (current.DeclaredAccessibility != Accessibility.Public)
            {
                return false;
            }
        }

        return true;
    }

    /// <summary>
    /// Returns <see langword="true"/> when <paramref name="type"/> has type parameters of its own or
    /// is nested inside a type that does.
    /// </summary>
    /// <remarks>
    /// A type nested inside a generic type is generic too, even when it declares no type parameter
    /// of its own -- which is why the containing chain has to be walked rather than
    /// <see cref="INamedTypeSymbol.Arity"/> read once. Generators that emit a non-generic top-level
    /// type per input use this to reject inputs that have no single closed form to write.
    /// </remarks>
    /// <param name="type">The type to inspect.</param>
    /// <returns><see langword="true"/> when the type carries type parameters at any level.</returns>
    public static bool IsGenericOrNestedInGeneric(INamedTypeSymbol type)
    {
        for (INamedTypeSymbol? current = type; current is not null; current = current.ContainingType)
        {
            if (current.Arity > 0)
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Whether <paramref name="accessibility"/> lets another file of the same assembly use the
    /// declaration.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <c>protected internal</c> qualifies (it is <i>internal or</i> protected, and the generated
    /// file gets the <c>internal</c> half); <c>private protected</c> does not (it is <i>internal
    /// and</i> protected, and generated code that derives from nothing never gets the
    /// <c>protected</c> half).
    /// </para>
    /// <para>
    /// <see cref="Accessibility.NotApplicable"/> is treated as <b>not</b> usable. Every
    /// <see cref="INamedTypeSymbol"/> that reports it is an <see cref="IErrorTypeSymbol"/> -- an
    /// unresolved name, or the placeholder "type argument" of an unbound generic type -- so
    /// answering "usable" would invite a generator to emit a reference to a name that does not
    /// resolve, turning the user's one compiler error into that error plus a second one inside a
    /// generated file they cannot edit. (The other symbol kinds that report
    /// <see cref="Accessibility.NotApplicable"/> -- type parameters, <c>dynamic</c>, array and
    /// pointer types -- are not named types and so never reach a nesting-chain walk; namespaces
    /// report <see cref="Accessibility.Public"/>, not this value.)
    /// </para>
    /// </remarks>
    /// <param name="accessibility">The declared accessibility to classify.</param>
    /// <returns><see langword="true"/> for <c>public</c>, <c>internal</c> and <c>protected internal</c>.</returns>
    public static bool IsAtLeastInternal(Accessibility accessibility) =>
        accessibility is Accessibility.Public or Accessibility.Internal or Accessibility.ProtectedOrInternal;

    /// <summary>
    /// Returns <see langword="true"/> when generated code in a separate file of the same assembly
    /// may name <paramref name="type"/>.
    /// </summary>
    /// <param name="type">The type to inspect.</param>
    /// <returns><see langword="true"/> when the type is nameable from generated code.</returns>
    public static bool IsAccessibleFromGeneratedCode(INamedTypeSymbol type) =>
        FindGeneratedCodeAccessBlocker(type) is null;

    /// <summary>
    /// Returns the first link of <paramref name="type"/>'s nesting chain that generated code in a
    /// separate file of the same assembly cannot name, or <see langword="null"/> when the whole
    /// chain is nameable.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The whole nesting chain is walked, because a <see langword="public"/> type nested in a
    /// <see langword="private"/> one is no more reachable than a private one. "Nameable" means
    /// <c>internal</c> or wider at every step and file-local at no step: a generated file is a
    /// separate file of the same assembly, so it sees everything the assembly sees, but nothing
    /// that a declaration keeps to itself
    /// (<c>private</c>/<c>protected</c>/<c>private protected</c>) and nothing that another file
    /// keeps to itself. A <c>file</c>-local type is <c>internal</c> as far as
    /// <see cref="ISymbol.DeclaredAccessibility"/> is concerned, so it has to be asked about
    /// separately.
    /// </para>
    /// <para>
    /// The blocking symbol is returned rather than a bare <see cref="bool"/> so a caller that
    /// reports a diagnostic can name it: whether it is the type itself or a container, and whether
    /// it is file-local or merely too private, is exactly what makes such a message actionable.
    /// Callers that only need the yes/no answer should use
    /// <see cref="IsAccessibleFromGeneratedCode"/>.
    /// </para>
    /// <para>
    /// This is deliberately a property of the type alone rather than of the type and whatever
    /// container would name it: a type nested privately inside some container would in fact be
    /// reachable from that one container's generated part, but making the rule depend on where the
    /// type happens to be used would mean the same declaration is legal or illegal depending on a
    /// second file.
    /// </para>
    /// </remarks>
    /// <param name="type">The type to inspect.</param>
    /// <returns>The blocking type, or <see langword="null"/>.</returns>
    public static INamedTypeSymbol? FindGeneratedCodeAccessBlocker(INamedTypeSymbol type)
    {
        for (INamedTypeSymbol? current = type; current is not null; current = current.ContainingType)
        {
            if (current.IsFileLocal || !IsAtLeastInternal(current.DeclaredAccessibility))
            {
                return current;
            }
        }

        return null;
    }

    /// <summary>
    /// Orders diagnostics by source position (then id) so a run's diagnostic sequence is a function
    /// of the compilation alone rather than of the order pipeline nodes happened to run in.
    /// Diagnostics without a source location sort last (<c>false</c> orders before <c>true</c>).
    /// </summary>
    /// <param name="diagnostics">The diagnostics to order.</param>
    /// <returns>The same diagnostics in a deterministic order.</returns>
    public static ImmutableArray<DiagnosticInfo> SortForDiagnosticDeterminism(
        ImmutableArray<DiagnosticInfo> diagnostics) =>
        diagnostics
            .OrderBy(diagnostic => diagnostic.Location is null)
            .ThenBy(diagnostic => diagnostic.Location?.FilePath ?? string.Empty, StringComparer.Ordinal)
            .ThenBy(diagnostic => diagnostic.Location?.TextSpan.Start ?? 0)
            .ThenBy(diagnostic => diagnostic.Descriptor.Id, StringComparer.Ordinal)
            .ToImmutableArray();
}
