using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

namespace SsalKit.Generators.Toolkit.Testing.Tests.Harness;

/// <summary>
/// A well-behaved incremental generator, small enough to reason about completely, that exercises
/// everything the harness has to be able to observe: named tracking stages whose models are
/// value-equal across runs, one generated file per decorated type, an error reported on the
/// attribute, and a warning reported with no location at all.
/// </summary>
/// <remarks>
/// Testing the harness against real generators would only prove the two agree; a generator whose
/// every output is decided here is what lets a test assert that the harness reports a cache hit
/// when there is one and a cache miss when there is not.
/// </remarks>
public sealed class MiniGenerator : IIncrementalGenerator
{
    public const string AttributeMetadataName = "Mini.MarkerAttribute";

    /// <summary>Reported on a type whose name starts with <c>Bad</c>, on the attribute itself.</summary>
    public static readonly DiagnosticDescriptor BadName = new(
        "MINI001",
        "Marked type is named Bad",
        "Type '{0}' must not be named Bad",
        "MiniGenerator",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Reported on a type whose name starts with <c>Odd</c>, with no location at all.</summary>
    public static readonly DiagnosticDescriptor OddName = new(
        "MINI002",
        "Marked type is named Odd",
        "Type '{0}' is named Odd",
        "MiniGenerator",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public static class TrackingNames
    {
        public const string Models = "MiniModels";
        public const string Collected = "MiniCollected";
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeMetadataName,
                static (_, _) => true,
                static (syntaxContext, _) => CreateModel(syntaxContext))
            .WithTrackingName(TrackingNames.Models);

        var collected = models.Collect().WithTrackingName(TrackingNames.Collected);

        context.RegisterSourceOutput(collected, static (context, models) => Emit(context, models));
    }

    private static MiniModel CreateModel(GeneratorAttributeSyntaxContext syntaxContext)
    {
        var symbol = (INamedTypeSymbol)syntaxContext.TargetSymbol;
        var attribute = syntaxContext.Attributes[0];
        var greeting = (string?)attribute.ConstructorArguments[0].Value ?? string.Empty;

        var diagnosticId = symbol.Name switch
        {
            var name when name.StartsWith("Bad", StringComparison.Ordinal) => BadName.Id,
            var name when name.StartsWith("Odd", StringComparison.Ordinal) => OddName.Id,
            _ => null,
        };

        return new MiniModel(
            symbol.ContainingNamespace.IsGlobalNamespace ? string.Empty : symbol.ContainingNamespace.ToDisplayString(),
            symbol.Name,
            greeting,
            diagnosticId,
            MiniLocation.From(attribute.ApplicationSyntaxReference!));
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<MiniModel> models)
    {
        foreach (var model in models)
        {
            if (model.DiagnosticId == BadName.Id)
            {
                context.ReportDiagnostic(
                    Diagnostic.Create(BadName, model.Location.ToLocation(), model.TypeName));
                continue;
            }

            if (model.DiagnosticId == OddName.Id)
            {
                context.ReportDiagnostic(Diagnostic.Create(OddName, Location.None, model.TypeName));
                continue;
            }

            context.AddSource($"{model.TypeName}.Mini.g.cs", Render(model));
        }
    }

    private static string Render(MiniModel model)
    {
        var builder = new StringBuilder("// <auto-generated/>").AppendLine();

        if (model.Namespace.Length != 0)
        {
            builder.Append("namespace ").Append(model.Namespace).AppendLine(";").AppendLine();
        }

        builder
            .Append("public static class ").Append(model.TypeName).AppendLine("Greeter")
            .AppendLine("{")
            .Append("    public const string Greeting = \"").Append(model.Greeting).AppendLine("\";")
            .AppendLine("}");

        return builder.ToString();
    }
}
