using System.Runtime.CompilerServices;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SsalKit.Generators.Toolkit.Tests;

/// <summary>
/// Regression guard for the packaging contract in the design doc: every embedded source file
/// under <c>src/SsalKit.Generators.Toolkit</c> must start with the fixed 3-line header, avoid
/// <c>record</c>/init-only syntax, stay inside C# 10, declare only <c>internal</c> types, live in
/// the fixed toolkit namespace, and never rely on <see cref="System.Environment.NewLine"/> (output
/// must be deterministic across host operating systems).
/// </summary>
/// <remarks>
/// The syntax-shaped rules are checked by parsing each file with Roslyn rather than by scanning its
/// text: a text scan cannot tell a <c>record</c> declaration from the word "record" inside a
/// documentation comment, which matters now that the package documents the very syntax it forbids
/// itself.
/// </remarks>
public class EmbeddedSourceConventionTests
{
    /// <summary>
    /// The one embedded file that is deliberately exempt from the namespace rule: the compiler
    /// looks the polyfill type up by its fixed fully qualified name, so it cannot be moved.
    /// </summary>
    private const string PolyfillFileName = "IsExternalInit.cs";

    private const string PolyfillNamespace = "System.Runtime.CompilerServices";

    private const string ToolkitNamespace = "SsalKit.Generators.Toolkit";

    /// <summary>
    /// The preprocessor symbol a consumer defines to drop the polyfill from its compilation.
    /// </summary>
    private const string PolyfillOptOutSymbol = "SSALKIT_GENERATORS_TOOLKIT_EXCLUDE_ISEXTERNALINIT";

    private static readonly string[] SourceFiles = GetSourceFiles();

    [Fact]
    public void SourceFiles_AllShippedComponentsFound()
    {
        var names = SourceFiles.Select(Path.GetFileName).ToArray();

        Assert.Equal(
            new[]
            {
                "AttributeLocations.cs",
                "CSharpNaming.cs",
                "DiagnosticDescriptorFactory.cs",
                "DiagnosticInfo.cs",
                "EquatableArray.cs",
                "HintNameSanitizer.cs",
                "IndentedCodeWriter.cs",
                "IsExternalInit.cs",
                "SymbolFacts.cs",
            },
            names.OrderBy(name => name, StringComparer.Ordinal).ToArray());
    }

    [Theory]
    [MemberData(nameof(SourceFileCases))]
    public void SourceFile_StartsWithFixedThreeLineHeader(string path)
    {
        var lines = File.ReadAllLines(path);

        Assert.True(lines.Length >= 3, $"{Path.GetFileName(path)} has fewer than 3 lines.");
        Assert.Equal("// <auto-generated/>", lines[0]);
        Assert.Equal("#pragma warning disable", lines[1]);
        Assert.Equal("#nullable enable", lines[2]);
    }

    [Theory]
    [MemberData(nameof(SourceFileCases))]
    public void SourceFile_DoesNotUseRecordOrInitOnlySyntax(string path)
    {
        var root = Parse(path).GetRoot();

        var recordDeclarations = root.DescendantNodes().OfType<RecordDeclarationSyntax>().ToArray();
        var initAccessors = root.DescendantNodes()
            .OfType<AccessorDeclarationSyntax>()
            .Where(accessor => accessor.IsKind(SyntaxKind.InitAccessorDeclaration))
            .ToArray();

        Assert.Empty(recordDeclarations);
        Assert.Empty(initAccessors);
    }

    [Theory]
    [MemberData(nameof(SourceFileCases))]
    public void SourceFile_ParsesAsCSharp10(string path)
    {
        var errors = Parse(path)
            .GetDiagnostics()
            .Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();

        Assert.Empty(errors);
    }

    [Theory]
    [MemberData(nameof(SourceFileCases))]
    public void SourceFile_DeclaresOnlyInternalTypes(string path)
    {
        var root = Parse(path).GetRoot();

        var publicTypes = root.DescendantNodes()
            .OfType<MemberDeclarationSyntax>()
            .Where(member => member is BaseTypeDeclarationSyntax or DelegateDeclarationSyntax)
            .Where(member => member.Modifiers.Any(SyntaxKind.PublicKeyword))
            .ToArray();

        Assert.Empty(publicTypes);
    }

    [Theory]
    [MemberData(nameof(SourceFileCases))]
    public void SourceFile_DeclaresTheFixedNamespace(string path)
    {
        var expected = Path.GetFileName(path) == PolyfillFileName ? PolyfillNamespace : ToolkitNamespace;

        var declared = Parse(path).GetRoot()
            .DescendantNodes()
            .OfType<BaseNamespaceDeclarationSyntax>()
            .Select(declaration => declaration.Name.ToString())
            .ToArray();

        Assert.Equal(new[] { expected }, declared);
    }

    [Theory]
    [MemberData(nameof(SourceFileCases))]
    public void SourceFile_DoesNotUseEnvironmentNewLine(string path)
    {
        var text = File.ReadAllText(path);

        Assert.DoesNotContain("Environment.NewLine", text);
    }

    /// <summary>
    /// Embedded sources are compiled with the <em>consumer's</em> options, and
    /// <c>&lt;CheckForOverflowUnderflow&gt;true&lt;/CheckForOverflowUnderflow&gt;</c> turns every
    /// arithmetic operation in the file into a checked one. A hash accumulator is the one place that
    /// deliberately relies on wrap-around, so an unwrapped one throws
    /// <see cref="OverflowException"/> at run time in such a project -- from inside a file its
    /// author cannot edit, on a code path (equality) that has nothing to do with what they were
    /// doing.
    /// </summary>
    [Theory]
    [MemberData(nameof(SourceFileCases))]
    public void SourceFile_HashCodeArithmetic_IsExplicitlyUnchecked(string path)
    {
        var hashMethods = Parse(path).GetRoot()
            .DescendantNodes()
            .OfType<MethodDeclarationSyntax>()
            .Where(method => method.Identifier.ValueText == "GetHashCode")
            .ToArray();

        foreach (var method in hashMethods)
        {
            var unprotected = method.DescendantNodes()
                .OfType<BinaryExpressionSyntax>()
                .Where(IsArithmetic)
                .Where(expression => !expression.Ancestors().Any(IsUncheckedContext))
                .ToArray();

            Assert.Empty(unprotected);
        }
    }

    /// <summary>
    /// A <c>global using</c> in an embedded file would apply to every file of the consumer's
    /// compilation, silently changing how names bind in source the package never sees.
    /// </summary>
    [Theory]
    [MemberData(nameof(SourceFileCases))]
    public void SourceFile_DeclaresNoGlobalUsing(string path)
    {
        var globalUsings = Parse(path).GetRoot()
            .DescendantNodes()
            .OfType<UsingDirectiveSyntax>()
            .Where(directive => !directive.GlobalKeyword.IsKind(SyntaxKind.None))
            .ToArray();

        Assert.Empty(globalUsings);
    }

    private static bool IsArithmetic(BinaryExpressionSyntax expression) =>
        expression.IsKind(SyntaxKind.MultiplyExpression)
        || expression.IsKind(SyntaxKind.AddExpression)
        || expression.IsKind(SyntaxKind.SubtractExpression);

    private static bool IsUncheckedContext(SyntaxNode node) =>
        (node is CheckedStatementSyntax statement && statement.Keyword.IsKind(SyntaxKind.UncheckedKeyword))
        || (node is CheckedExpressionSyntax expression && expression.Keyword.IsKind(SyntaxKind.UncheckedKeyword));

    [Fact]
    public void Polyfill_WithoutOptOutSymbol_DeclaresIsExternalInit()
    {
        var root = Parse(PolyfillPath()).GetRoot();

        var declared = root.DescendantNodes()
            .OfType<BaseTypeDeclarationSyntax>()
            .Select(type => type.Identifier.ValueText)
            .ToArray();

        Assert.Equal(new[] { "IsExternalInit" }, declared);
    }

    [Fact]
    public void Polyfill_WithOptOutSymbol_DeclaresNothing()
    {
        var root = Parse(PolyfillPath(), PolyfillOptOutSymbol).GetRoot();

        Assert.Empty(root.DescendantNodes().OfType<MemberDeclarationSyntax>());
        Assert.Empty(root.DescendantNodes().OfType<BaseNamespaceDeclarationSyntax>());
    }

    [Fact]
    public void Polyfill_DocumentsTheOptOutSymbol()
    {
        var text = File.ReadAllText(PolyfillPath());

        Assert.Contains("#if !" + PolyfillOptOutSymbol, text);
    }

    /// <summary>
    /// The polyfill is the only file allowed to carry conditional compilation: everything else must
    /// compile identically in every consumer, whatever their <c>DefineConstants</c> happen to be.
    /// </summary>
    [Theory]
    [MemberData(nameof(SourceFileCases))]
    public void SourceFile_OtherThanThePolyfill_HasNoConditionalCompilation(string path)
    {
        if (Path.GetFileName(path) == PolyfillFileName)
        {
            return;
        }

        Assert.DoesNotContain("#if", File.ReadAllText(path));
    }

    public static IEnumerable<object[]> SourceFileCases() =>
        SourceFiles.Select(path => new object[] { path });

    private static SyntaxTree Parse(string path, params string[] preprocessorSymbols) =>
        CSharpSyntaxTree.ParseText(
            File.ReadAllText(path),
            new CSharpParseOptions(LanguageVersion.CSharp10, preprocessorSymbols: preprocessorSymbols),
            path);

    private static string PolyfillPath() =>
        SourceFiles.Single(path => Path.GetFileName(path) == PolyfillFileName);

    private static string[] GetSourceFiles([CallerFilePath] string testFilePath = "")
    {
        var testsDirectory = Path.GetDirectoryName(testFilePath)!;
        var srcDirectory = Path.GetFullPath(
            Path.Combine(testsDirectory, "..", "..", "src", "SsalKit.Generators.Toolkit"));

        return Directory.GetFiles(srcDirectory, "*.cs", SearchOption.TopDirectoryOnly);
    }
}
