using System.Runtime.CompilerServices;
using System.Text.RegularExpressions;

namespace SsalKit.Generators.Toolkit.Tests;

/// <summary>
/// Regression guard for the packaging contract in the design doc: every embedded source file
/// under <c>src/SsalKit.Generators.Toolkit</c> must start with the fixed 3-line header, avoid
/// <c>record</c>/init-only syntax (no <c>IsExternalInit</c> polyfill is shipped), declare only
/// <c>internal</c> types, and never rely on <see cref="System.Environment.NewLine"/> (output must
/// be deterministic across host operating systems).
/// </summary>
public class EmbeddedSourceConventionTests
{
    private static readonly string[] SourceFiles = GetSourceFiles();

    [Fact]
    public void SourceFiles_AtLeastFiveFilesFound()
    {
        Assert.True(SourceFiles.Length >= 5, $"Expected at least 5 embedded source files, found {SourceFiles.Length}.");
    }

    [Theory]
    [MemberData(nameof(SourceFileCases))]
    public void SourceFile_StartsWithFixedThreeLineHeader(string path)
    {
        var lines = File.ReadAllLines(path);

        Assert.True(lines.Length >= 3, $"{Path.GetFileName(path)} has fewer than 3 lines.");
        Assert.Equal("// <auto-generated/>", lines[0]);
        Assert.Equal("#pragma warning disable", lines[1]);
        Assert.Equal("#nullable enable", lines[2]);
    }

    [Theory]
    [MemberData(nameof(SourceFileCases))]
    public void SourceFile_DoesNotUseRecordOrInitOnlySyntax(string path)
    {
        var text = File.ReadAllText(path);

        Assert.DoesNotContain("record ", text);
        Assert.DoesNotContain(" init", text);
        Assert.DoesNotContain("init;", text);
    }

    [Theory]
    [MemberData(nameof(SourceFileCases))]
    public void SourceFile_DeclaresOnlyInternalTypes(string path)
    {
        var text = File.ReadAllText(path);

        var publicTypeDeclaration = new Regex(
            @"^\s*public\s+(?:sealed\s+|abstract\s+|static\s+|readonly\s+|partial\s+|unsafe\s+)*(class|struct|interface|enum|delegate|record)\s",
            RegexOptions.Multiline);

        Assert.False(publicTypeDeclaration.IsMatch(text), $"{Path.GetFileName(path)} declares a public type.");
    }

    [Theory]
    [MemberData(nameof(SourceFileCases))]
    public void SourceFile_DoesNotUseEnvironmentNewLine(string path)
    {
        var text = File.ReadAllText(path);

        Assert.DoesNotContain("Environment.NewLine", text);
    }

    public static IEnumerable<object[]> SourceFileCases() =>
        SourceFiles.Select(path => new object[] { path });

    private static string[] GetSourceFiles([CallerFilePath] string testFilePath = "")
    {
        var testsDirectory = Path.GetDirectoryName(testFilePath)!;
        var srcDirectory = Path.GetFullPath(
            Path.Combine(testsDirectory, "..", "..", "src", "SsalKit.Generators.Toolkit"));

        return Directory.GetFiles(srcDirectory, "*.cs", SearchOption.TopDirectoryOnly);
    }
}
