using System.Linq.Expressions;
using SsalKit.Generators.Toolkit;

namespace SsalKit.Generators.Toolkit.Tests;

/// <summary>
/// Direct unit tests for <see cref="IndentedCodeWriter"/>: line writing, blank-line handling,
/// nested indentation scopes, block scopes (default and custom closer), the header helper, and
/// both documentation-line overloads.
/// </summary>
public class IndentedCodeWriterTests
{
    [Fact]
    public void WriteAutoGeneratedHeader_WritesHeaderNullableAndBlankLine()
    {
        var writer = new IndentedCodeWriter();

        writer.WriteAutoGeneratedHeader();

        Assert.Equal("// <auto-generated/>\n#nullable enable\n\n", writer.ToString());
    }

    /// <summary>
    /// The pragma is opt-in, so the header every existing generator emits is byte-for-byte what it
    /// was before the parameter existed -- which is what keeps their snapshots from churning.
    /// </summary>
    [Fact]
    public void WriteAutoGeneratedHeader_DefaultsToTheHeaderWithoutThePragma()
    {
        var withoutArgument = new IndentedCodeWriter();
        var explicitlyFalse = new IndentedCodeWriter();

        withoutArgument.WriteAutoGeneratedHeader();
        explicitlyFalse.WriteAutoGeneratedHeader(suppressWarnings: false);

        Assert.Equal(withoutArgument.ToString(), explicitlyFalse.ToString());
        Assert.DoesNotContain("#pragma", withoutArgument.ToString(), StringComparison.Ordinal);
    }

    [Fact]
    public void WriteAutoGeneratedHeader_SuppressingWarnings_PutsThePragmaBeforeTheNullableDirective()
    {
        var writer = new IndentedCodeWriter();

        writer.WriteAutoGeneratedHeader(suppressWarnings: true);

        Assert.Equal(
            "// <auto-generated/>\n#pragma warning disable\n#nullable enable\n\n", writer.ToString());
    }

    [Fact]
    public void WriteLine_MultipleLines_AreSeparatedByLineFeedOnly()
    {
        var writer = new IndentedCodeWriter();

        writer.WriteLine("first");
        writer.WriteLine("second");

        Assert.Equal("first\nsecond\n", writer.ToString());
    }

    [Fact]
    public void WriteLine_Parameterless_WritesBlankLineWithoutIndentation()
    {
        var writer = new IndentedCodeWriter();

        using (writer.Indent())
        {
            writer.WriteLine("x");
            writer.WriteLine();
            writer.WriteLine("y");
        }

        Assert.Equal("    x\n\n    y\n", writer.ToString());
    }

    [Fact]
    public void WriteLine_EmptyString_BehavesLikeBlankLine()
    {
        var writer = new IndentedCodeWriter();

        using (writer.Indent())
        {
            writer.WriteLine(string.Empty);
        }

        Assert.Equal("\n", writer.ToString());
    }

    [Fact]
    public void Write_EmptyString_IsNoOpAndDoesNotConsumePendingIndent()
    {
        var writer = new IndentedCodeWriter();

        using (writer.Indent())
        {
            writer.Write(string.Empty);
            writer.Write("abc");
            writer.WriteLine();
        }

        Assert.Equal("    abc\n", writer.ToString());
    }

    [Fact]
    public void Write_MultipleCallsOnSameLine_IndentsOnlyOnce()
    {
        var writer = new IndentedCodeWriter();

        writer.Write("abc");
        writer.Write("def");
        writer.WriteLine();

        Assert.Equal("abcdef\n", writer.ToString());
    }

    [Fact]
    public void Indent_NestedScopes_IncreaseAndRestoreIndentationLevel()
    {
        var writer = new IndentedCodeWriter();

        writer.WriteLine("level0");
        using (writer.Indent())
        {
            writer.WriteLine("level1");
            using (writer.Indent())
            {
                writer.WriteLine("level2");
            }

            writer.WriteLine("back-to-level1");
        }

        writer.WriteLine("back-to-level0");

        Assert.Equal(
            "level0\n    level1\n        level2\n    back-to-level1\nback-to-level0\n",
            writer.ToString());
    }

    [Fact]
    public void Indent_CustomIndentSize_ControlsSpaceCount()
    {
        var writer = new IndentedCodeWriter(indentSize: 2);

        writer.WriteLine("a");
        using (writer.Indent())
        {
            writer.WriteLine("b");
        }

        Assert.Equal("a\n  b\n", writer.ToString());
    }

    [Fact]
    public void Block_DefaultCloser_WritesOpeningAndClosingBrace()
    {
        var writer = new IndentedCodeWriter();

        using (writer.Block("public class Bar"))
        {
            writer.WriteLine("public int X;");
        }

        Assert.Equal("public class Bar\n{\n    public int X;\n}\n", writer.ToString());
    }

    [Fact]
    public void Block_Nested_IndentsEachLevel()
    {
        var writer = new IndentedCodeWriter();

        using (writer.Block("public class Outer"))
        {
            using (writer.Block("public void Method()"))
            {
                writer.WriteLine("DoWork();");
            }
        }

        Assert.Equal(
            "public class Outer\n{\n    public void Method()\n    {\n        DoWork();\n    }\n}\n",
            writer.ToString());
    }

    [Fact]
    public void Block_CustomCloser_WritesSuppliedClosingToken()
    {
        var writer = new IndentedCodeWriter();

        using (writer.Block("var obj = new", "};"))
        {
            writer.WriteLine("A = 1,");
        }

        Assert.Equal("var obj = new\n{\n    A = 1,\n};\n", writer.ToString());
    }

    [Fact]
    public void ToString_ReflectsAllWritesInOrder()
    {
        var writer = new IndentedCodeWriter();

        writer.WriteLine("a");
        writer.WriteLine("b");

        Assert.Equal("a\nb\n", writer.ToString());
        Assert.Equal("a\nb\n", writer.ToString());
    }

    [Fact]
    public void WriteDocLine_PrefixesContentWithTripleSlashAndSpace()
    {
        var writer = new IndentedCodeWriter();

        writer.WriteDocLine("<summary>");

        Assert.Equal("/// <summary>\n", writer.ToString());
    }

    [Fact]
    public void WriteDocLine_EmptyContent_WritesBareTripleSlashWithoutTrailingSpace()
    {
        var writer = new IndentedCodeWriter();

        writer.WriteDocLine(string.Empty);

        Assert.Equal("///\n", writer.ToString());
    }

    [Fact]
    public void WriteDocLine_InsideBlock_IsIndented()
    {
        var writer = new IndentedCodeWriter();

        using (writer.Block("internal static class C"))
        {
            writer.WriteDocLine("<summary>Docs.</summary>");
        }

        Assert.Equal("internal static class C\n{\n    /// <summary>Docs.</summary>\n}\n", writer.ToString());
    }

    [Fact]
    public void WriteDocLines_WritesOneLinePerElementInOrder()
    {
        var writer = new IndentedCodeWriter();

        writer.WriteDocLines(
            "<summary>",
            "Picks an item.",
            "</summary>",
            string.Empty,
            "<returns>The item.</returns>");

        Assert.Equal(
            "/// <summary>\n/// Picks an item.\n/// </summary>\n///\n/// <returns>The item.</returns>\n",
            writer.ToString());
    }

    [Fact]
    public void WriteDocLines_WithNoArguments_WritesNothing()
    {
        var writer = new IndentedCodeWriter();

        writer.WriteDocLines();

        Assert.Equal(string.Empty, writer.ToString());
    }

    [Fact]
    public void WriteDocLines_Sequence_WritesOneLinePerElementInOrder()
    {
        var writer = new IndentedCodeWriter();

        writer.WriteDocLines(new List<string>
        {
            "<summary>",
            "Picks an item.",
            "</summary>",
            string.Empty,
            "<returns>The item.</returns>",
        });

        Assert.Equal(
            "/// <summary>\n/// Picks an item.\n/// </summary>\n///\n/// <returns>The item.</returns>\n",
            writer.ToString());
    }

    [Fact]
    public void WriteDocLines_EmptySequence_WritesNothing()
    {
        var writer = new IndentedCodeWriter();

        writer.WriteDocLines(Enumerable.Empty<string>());

        Assert.Equal(string.Empty, writer.ToString());
    }

    [Fact]
    public void WriteDocLines_Sequence_IsIndentedLikeAnyOtherLine()
    {
        var writer = new IndentedCodeWriter();

        using (writer.Block("internal static class C"))
        {
            writer.WriteDocLines(new[] { "<summary>", "Docs.", "</summary>" }.AsEnumerable());
        }

        Assert.Equal(
            "internal static class C\n{\n    /// <summary>\n    /// Docs.\n    /// </summary>\n}\n",
            writer.ToString());
    }

    /// <summary>
    /// The overload is meant for lazily assembled documentation, so it must enumerate as it writes
    /// rather than buffer first -- and must do so exactly once, since a deferred query is free to
    /// be expensive (or single-pass) on a second enumeration.
    /// </summary>
    [Fact]
    public void WriteDocLines_DeferredSequence_IsEnumeratedExactlyOnceAndLazily()
    {
        var writer = new IndentedCodeWriter();
        var enumerations = 0;

        IEnumerable<string> Contents()
        {
            enumerations++;
            yield return "<summary>";
            yield return "Docs.";
            yield return "</summary>";
        }

        var deferred = Contents();
        Assert.Equal(0, enumerations);

        writer.WriteDocLines(deferred);

        Assert.Equal(1, enumerations);
        Assert.Equal("/// <summary>\n/// Docs.\n/// </summary>\n", writer.ToString());
    }

    /// <summary>
    /// The conditional-assembly case the overload was added for: a run of doc lines built up with
    /// optional pieces, passed straight to the writer without being materialized into an array.
    /// </summary>
    [Theory]
    [InlineData(true, "/// <summary>\n/// Docs.\n/// </summary>\n/// <remarks>Extra.</remarks>\n")]
    [InlineData(false, "/// <summary>\n/// Docs.\n/// </summary>\n")]
    public void WriteDocLines_ConditionallyExtendedSequence_WritesOnlyTheIncludedLines(
        bool includeRemarks, string expected)
    {
        var writer = new IndentedCodeWriter();

        var contents = new[] { "<summary>", "Docs.", "</summary>" }
            .Concat(includeRemarks ? new[] { "<remarks>Extra.</remarks>" } : Enumerable.Empty<string>());

        writer.WriteDocLines(contents);

        Assert.Equal(expected, writer.ToString());
    }

    /// <summary>
    /// Overload resolution regression guard: <c>string[]</c> is the more specific parameter type, so
    /// every pre-existing call site -- loose arguments, an explicit array, no arguments at all --
    /// must still bind to the <c>params</c> overload now that a sequence overload exists.
    /// </summary>
    [Fact]
    public void WriteDocLines_ArrayAndLooseArguments_StillBindToTheParamsOverload()
    {
        var array = new[] { "<summary>", "Docs.", "</summary>" };

        Assert.Equal(typeof(string[]), BoundParameterTypeOf(() => new IndentedCodeWriter().WriteDocLines(array)));
        Assert.Equal(
            typeof(string[]),
            BoundParameterTypeOf(() => new IndentedCodeWriter().WriteDocLines("<summary>", "</summary>")));
        Assert.Equal(typeof(string[]), BoundParameterTypeOf(() => new IndentedCodeWriter().WriteDocLines("Docs.")));
        Assert.Equal(typeof(string[]), BoundParameterTypeOf(() => new IndentedCodeWriter().WriteDocLines()));

        Assert.Equal(
            typeof(IEnumerable<string>),
            BoundParameterTypeOf(() => new IndentedCodeWriter().WriteDocLines(array.AsEnumerable())));
    }

    /// <summary>
    /// Reads back which <c>WriteDocLines</c> overload the C# compiler picked for a call, by
    /// inspecting the method the expression tree recorded.
    /// </summary>
    private static Type BoundParameterTypeOf(Expression<Action> call) =>
        ((MethodCallExpression)call.Body).Method.GetParameters()[0].ParameterType;
}
